/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2019-03-09 09:29:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.train.temp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bdjzcs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/c.tld", Long.valueOf(1546843288000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<title>标定基准参数</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("        <div data-options=\"region:'north',split:false,collapsible:false,title:'条件查询'\" style=\"height:90px;\">\r\n");
      out.write("            <div style=\"margin:10px\">\r\n");
      out.write("                <label>设备号：</label>\r\n");
      out.write(" \t\t\t\t<input class=\"easyui-textbox\" name=\"key-sw-id\" id=\"key-sw-id\" style=\"width:150px\">\r\n");
      out.write(" \t\t\t\t<label>当前状态：</label>\r\n");
      out.write("\t \t\t\t<select class=\"easyui-combobox\" id=\"key_sw_zt\" data-options=\"editable:false\" style=\"width:150px;\">\r\n");
      out.write(" \t\t\t\t\t<option value=\"all\">全部</option>\r\n");
      out.write(" \t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write(" \t\t\t\t</select>\r\n");
      out.write("                <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" onclick=\"query()\">查询</a>\r\n");
      out.write("                <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-undo\" onclick=\"reset()\">重置</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div data-options=\"region:'center'\">\r\n");
      out.write("        \t<table id=\"dg\" class=\"easyui-datagrid\"></table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        /**\r\n");
      out.write("        * Name 添加记录\r\n");
      out.write("        */\r\n");
      out.write("        function add(){\r\n");
      out.write("            $.ajax({\r\n");
      out.write("            \ttype: 'POST',\r\n");
      out.write("                url:'equ/addJccs.do',\r\n");
      out.write("                data: $('#bdjzcs-form').serialize(),\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                success:function(data){\r\n");
      out.write("                    var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("                    if(data && 'Y' == data.state){\r\n");
      out.write("                        $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                        $('#dialog').dialog('destroy');\r\n");
      out.write("                    }else{\r\n");
      out.write("                        $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                    }\r\n");
      out.write("                    $('#dg').datagrid('reload');\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 修改记录\r\n");
      out.write("        */\r\n");
      out.write("        function edit(){\r\n");
      out.write("            $.ajax({\r\n");
      out.write("            \ttype: 'POST',\r\n");
      out.write("                url:'equ/updateJccs.do',\r\n");
      out.write("                data: $('#bdjzcs-form').serialize(),\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                success:function(data){\r\n");
      out.write("                    var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("                    if(data && 'Y' == data.state){\r\n");
      out.write("                        $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                        $('#dialog').dialog('destroy');\r\n");
      out.write("                    }else{\r\n");
      out.write("                        $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                    }\r\n");
      out.write("                    $('#dg').datagrid('reload');\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 删除记录\r\n");
      out.write("        */\r\n");
      out.write("        function remove(){\r\n");
      out.write("            var item = $('#dg').datagrid('getSelected');\r\n");
      out.write("            if(!item){\r\n");
      out.write("                $.messager.alert('提醒','请选择需要删除的记录!');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            $.messager.confirm('信息提示','确定要删除该记录？', function(result){\r\n");
      out.write("                if(result){\r\n");
      out.write("                    $.ajax({\r\n");
      out.write("                    \ttype: 'POST',\r\n");
      out.write("                        url:'equ/deleteJccs.do',\r\n");
      out.write("                        data:{\r\n");
      out.write("                            id:item.id\r\n");
      out.write("                        },\r\n");
      out.write("                        dataType: \"json\",\r\n");
      out.write("                        success:function(data){\r\n");
      out.write("                            var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("                    \t\tif(data && 'Y' == data.state){\r\n");
      out.write("                                $.messager.alert('信息提示',returnMsg,'info');\t\t\r\n");
      out.write("                            }else{\r\n");
      out.write("                                $.messager.alert('信息提示',returnMsg,'info');\t\t\r\n");
      out.write("                            }\r\n");
      out.write("                            $('#dg').datagrid('reload');\r\n");
      out.write("                        }\t\r\n");
      out.write("                    });\r\n");
      out.write("                }\t\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 打开添加窗口\r\n");
      out.write("        */\r\n");
      out.write("        function openAdd(){\r\n");
      out.write("            $('<div id=\"dialog\"></div>').dialog({\r\n");
      out.write("                title: \"添加信息\",\r\n");
      out.write("                width: 700,\r\n");
      out.write("                height: 500,\r\n");
      out.write("                modal:true,\r\n");
      out.write("                closed: false,\r\n");
      out.write("                href: \"train/bdjzcs-dialog.do\",\r\n");
      out.write("                onClose:function(){  \r\n");
      out.write("                    $(this).dialog('destroy');  \r\n");
      out.write("                },\r\n");
      out.write("                buttons: [{\r\n");
      out.write("                    text: '确定',\r\n");
      out.write("                    iconCls: 'icon-ok',\r\n");
      out.write("                    handler: add\r\n");
      out.write("                }, {\r\n");
      out.write("                    text: '取消',\r\n");
      out.write("                    iconCls: 'icon-cancel',\r\n");
      out.write("                    handler: function () {\r\n");
      out.write("                        $('#dialog').dialog('close');                    \r\n");
      out.write("                    }\r\n");
      out.write("                }]\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 打开修改窗口\r\n");
      out.write("        */\r\n");
      out.write("        function openEdit(){\r\n");
      out.write("            var item = $('#dg').datagrid('getSelected');\r\n");
      out.write("            if(!item){\r\n");
      out.write("                $.messager.alert('提醒','请选择需要修改的记录!');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            $('<div id=\"dialog\"></div>').dialog({\r\n");
      out.write("                title: \"修改信息\",\r\n");
      out.write("                width: 700,\r\n");
      out.write("                height: 500,\r\n");
      out.write("                modal:true,\r\n");
      out.write("                closed: false,\r\n");
      out.write("                href: \"train/bdjzcs-dialog.do\",\r\n");
      out.write("                onClose:function(){  \r\n");
      out.write("                    $(this).dialog('destroy');  \r\n");
      out.write("                },\r\n");
      out.write("                onLoad:function(){\r\n");
      out.write("                \t$('#bdjzcs-form').form('load', item);\r\n");
      out.write("                },\r\n");
      out.write("                buttons: [{\r\n");
      out.write("                    text: '确定',\r\n");
      out.write("                    iconCls: 'icon-ok',\r\n");
      out.write("                    handler: edit\r\n");
      out.write("                }, {\r\n");
      out.write("                    text: '取消',\r\n");
      out.write("                    iconCls: 'icon-cancel',\r\n");
      out.write("                    handler: function () {\r\n");
      out.write("                        $('#dialog').dialog('close');                    \r\n");
      out.write("                    }\r\n");
      out.write("                }]\r\n");
      out.write("            });\r\n");
      out.write("        }\t\r\n");
      out.write("\r\n");
      out.write("        /*\r\n");
      out.write("        * 检索\r\n");
      out.write("        */\r\n");
      out.write("        function query(){\r\n");
      out.write("        \t$('#dg').datagrid('options').queryParams = {\r\n");
      out.write("            \tswinstrumentid: $(\"#key-sw-id\").val(),\r\n");
      out.write("                currentstatus: $(\"#key_sw_zt\").val()\r\n");
      out.write("            };\r\n");
      out.write("            $('#dg').datagrid(\"reload\");\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function reset(){\r\n");
      out.write("        \t$(\"#key_sw_zt\").combobox(\"setValue\",\"\"),\r\n");
      out.write("        \t$(\"#key-sw-id\").textbox(\"setValue\", \"\");\r\n");
      out.write("        \t$('#dg').datagrid('options').queryParams = {};\r\n");
      out.write("            $('#dg').datagrid(\"reload\");\r\n");
      out.write("        }\r\n");
      out.write("        /**\r\n");
      out.write("        * Name 载入数据\r\n");
      out.write("        */\r\n");
      out.write("        $('#dg').datagrid({\r\n");
      out.write("            url:'equ/jccsList.do',\r\n");
      out.write("            method:'post',\r\n");
      out.write("            singleSelect:true,\r\n");
      out.write("            footer:'#ft',\r\n");
      out.write("            rownumbers:true,\r\n");
      out.write("            pageSize:20,           \r\n");
      out.write("            pagination:true,\r\n");
      out.write("            multiSort:true,\r\n");
      out.write("            fitColumns:false,\r\n");
      out.write("            fit:true,\r\n");
      out.write("            border:false,\r\n");
      out.write("            striped: true,\r\n");
      out.write("            frozenColumns:[[\r\n");
      out.write("\t\t        { field:'',width:100,align:'center',checkbox:true},\r\n");
      out.write("\t\t        { field:'swinstrumentid',title:'检测仪序列号',width:120,align:'center'}\r\n");
      out.write("\t\t    ]],\r\n");
      out.write("            columns:[[\r\n");
      out.write("                { field:'currentstatus_name',title:'当前状态',width:100,align:'center'},\r\n");
      out.write("                { field:'meatime',title:'标定时间',width:100,align:'center'},\r\n");
      out.write("                { field:'materialref',title:'温度改正系数',width:130,align:'center'},\r\n");
      out.write("                { field:'lencd',title:'出厂CD',width:100,align:'center'},\r\n");
      out.write("                { field:'lenae',title:'出厂AE',width:100,align:'center'},\r\n");
      out.write("                { field:'lenbf',title:'出厂BF',width:100,align:'center'},\r\n");
      out.write("                { field:'lenh',title:'出厂H',width:100,align:'center'},\r\n");
      out.write("                { field:'wheeldiameter',title:'走行轮直径',width:100,align:'center'},\r\n");
      out.write("                { field:'lenac',title:'出厂AC',width:100,align:'center'},\r\n");
      out.write("                { field:'lenbd',title:'出厂BD',width:100,align:'center'},\r\n");
      out.write("                { field:'lenab',title:'出厂AB',width:100,align:'center'},\r\n");
      out.write("                { field:'leftdistsensorkl',title:'左棱镜至中心距离',width:150,align:'center'},\r\n");
      out.write("                { field:'rightdistsensorkr',title:'右棱镜至中心距离',width:150,align:'center'},\r\n");
      out.write("                { field:'distsensorat',title:'出厂AT',width:100,align:'center'},\r\n");
      out.write("                { field:'distsensorbt',title:'出厂BT',width:100,align:'center'},\r\n");
      out.write("                { field:'distsensorct',title:'出厂CT',width:100,align:'center'},\r\n");
      out.write("                { field:'distsensordt',title:'出厂DT',width:100,align:'center'},\r\n");
      out.write("                { field:'lenkl',title:'出厂KL',width:100,align:'center'},\r\n");
      out.write("                { field:'lenkr',title:'出厂KR',width:100,align:'center'},\r\n");
      out.write("                { field:'anglesensorxt',title:'出厂XT',width:100,align:'center'},\r\n");
      out.write("                { field:'anglesensoryt',title:'出厂YT',width:100,align:'center'},\r\n");
      out.write("                { field:'anglesensorkx',title:'出厂KX',width:100,align:'center'},\r\n");
      out.write("                { field:'anglesensorky',title:'出厂KY',width:100,align:'center'},\r\n");
      out.write("                { field:'temperature',title:'出厂标定温度',width:130,align:'center'},\r\n");
      out.write("                { field:'resolutionrate',title:'编码器分辨率',width:130,align:'center'},\r\n");
      out.write("                { field:'recordtime',title:'时间',width:150,align:'center'}                                       \r\n");
      out.write("            ]],\r\n");
      out.write("            toolbar: [{ \r\n");
      out.write("\t            text: '删除', \r\n");
      out.write("\t            iconCls: 'icon-remove', \r\n");
      out.write("\t            handler: remove\r\n");
      out.write("\t        }] \r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /train/temp/bdjzcs.jsp(20,6) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shebeizhuangtai}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /train/temp/bdjzcs.jsp(20,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write(" \t\t\t\t\t\t");
            if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fforEach_005f0_reused) {
        _jspx_th_c_005fforEach_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fchoose_005f0_reused) {
        _jspx_th_c_005fchoose_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fchoose_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /train/temp/bdjzcs.jsp(22,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.dd_desc==1}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.dd_desc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" selected>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.dd_value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fwhen_005f0_reused) {
        _jspx_th_c_005fwhen_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fwhen_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.dd_desc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.dd_value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fotherwise_005f0_reused) {
        _jspx_th_c_005fotherwise_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fotherwise_005f0);
      }
    }
    return false;
  }
}
