/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2019-03-09 09:27:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.train.temp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class department_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("\t\t<div data-options=\"region:'west',split:true,collapsible:false,title:'单位目录'\" style=\"width:250px;padding:10px;\">\r\n");
      out.write("\t\t\t<ul id=\"tt\" data-options=\"url:'sys/getDepTree.do'\"></ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div data-options=\"region:'center',border:false\">\r\n");
      out.write("\t\t\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("\t\t\t\t<div data-options=\"region:'north',split:false,collapsible:false,title:'条件查询'\" style=\"height:90px;\">\r\n");
      out.write("\t\t\t\t\t<div style=\"margin:10px\">\r\n");
      out.write("\t\t\t            <label>单位名称：</label><input id=\"key-dept\" class=\"easyui-textbox\"><input id=\"key-up-dept\" type=\"hidden\">\r\n");
      out.write("\t\t\t            <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" onclick=\"query()\">查询</a>\r\n");
      out.write("\t\t\t            <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-undo\" onclick=\"reset()\">重置</a>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div data-options=\"region:'center'\">\r\n");
      out.write("\t\t\t\t\t<table id=\"dg\" class=\"easyui-datagrid\"></table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("   \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        /**\r\n");
      out.write("        * Name 添加记录\r\n");
      out.write("        */\r\n");
      out.write("        function add(){\r\n");
      out.write("        \tif(!$(\"#dept-form\").form('enableValidation').form('validate')){\r\n");
      out.write("        \t\t$.messager.alert('信息提示',\"您有必填项目未填写，请填写完整！\",'info');\r\n");
      out.write("        \t\treturn false;\r\n");
      out.write("        \t}\r\n");
      out.write("        \t$.ajax({\r\n");
      out.write("            \ttype: 'POST',\r\n");
      out.write("                url:'");
      out.print(request.getContextPath());
      out.write("/sys/addDepartment.do',\r\n");
      out.write("                data: {\r\n");
      out.write("                \tdepart_name: $(\"#depart_name\").textbox(\"getValue\"),\r\n");
      out.write("                \tp_id: $('#tt').tree('getSelected').id,\r\n");
      out.write("               \t\tidPayDept: $(\"#idPayDept\").textbox(\"getValue\"),\r\n");
      out.write("            \t},\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                success:function(data){\r\n");
      out.write("                    var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("\t                if(data && 'Y' == data.state){\r\n");
      out.write("\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                    $('#dialog').dialog('close');\r\n");
      out.write("\t                }else{\r\n");
      out.write("\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                }\r\n");
      out.write("\t                $('#dg').datagrid('reload');\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 修改记录\r\n");
      out.write("        */\r\n");
      out.write("        function edit(){\r\n");
      out.write("        \tif(!$(\"#dept-form\").form('enableValidation').form('validate')){\r\n");
      out.write("        \t\t$.messager.alert('信息提示',\"您有必填项目未填写，请填写完整！\",'info');\r\n");
      out.write("        \t\treturn false;\r\n");
      out.write("        \t}\r\n");
      out.write("        \t$.ajax({\r\n");
      out.write("            \ttype: 'POST',\r\n");
      out.write("                url:'");
      out.print(request.getContextPath());
      out.write("/sys/updateDepartment.do',\r\n");
      out.write("                data: {\r\n");
      out.write("                \tdepart_id: $('#dg').datagrid('getSelected').depart_id,\r\n");
      out.write("                \tdepart_name: $(\"#depart_name\").textbox(\"getValue\"),\r\n");
      out.write("               \t\tidPayDept: $(\"#idPayDept\").textbox(\"getValue\"),\r\n");
      out.write("                },\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                success:function(data){\r\n");
      out.write("                    var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("\t                if(data && 'Y' == data.state){\r\n");
      out.write("\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                    $('#dialog').dialog('close');\r\n");
      out.write("\t                }else{\r\n");
      out.write("\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                }\r\n");
      out.write("\t                $('#dg').datagrid('reload');\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 删除记录\r\n");
      out.write("        */\r\n");
      out.write("        function remove(){\r\n");
      out.write("            var item = $('#dg').datagrid('getSelected');\r\n");
      out.write("            if(!item){\r\n");
      out.write("                $.messager.alert('提醒','请选择需要删除的记录!');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            $.messager.confirm('信息提示','确定要删除该记录？', function(result){\r\n");
      out.write("                if(result){\r\n");
      out.write("                    $.ajax({\r\n");
      out.write("                    \ttype: 'POST',\r\n");
      out.write("                        url:'");
      out.print(request.getContextPath());
      out.write("/sys/deleteDepartment.do',\r\n");
      out.write("                        data:{\r\n");
      out.write("                            depart_id: item.depart_id\r\n");
      out.write("                        },\r\n");
      out.write("                        dataType: \"json\",\r\n");
      out.write("                        success:function(data){\r\n");
      out.write("                            var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("                    \t\tif(data && 'Y' == data.state){\r\n");
      out.write("                        \t\t$.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                    \t\t}\r\n");
      out.write("                    \t\t$('#dg').datagrid('reload');\r\n");
      out.write("                        }\t\r\n");
      out.write("                    });\r\n");
      out.write("                }\t\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 打开添加窗口\r\n");
      out.write("        */\r\n");
      out.write("        function openAdd(){\r\n");
      out.write("        \tvar selected = $('#tt').tree('getSelected');\r\n");
      out.write("        \tif(!selected){\r\n");
      out.write("        \t\t$.messager.alert('提醒','请先选择上级单位！');\r\n");
      out.write("        \t\treturn;\r\n");
      out.write("        \t}\r\n");
      out.write("            \r\n");
      out.write("\t\t\t$('<div id=\"dialog\"></div>').dialog({\r\n");
      out.write("                title: \"修改信息\",\r\n");
      out.write("                width: 700,\r\n");
      out.write("                height: 400,\r\n");
      out.write("                modal:true,\r\n");
      out.write("                closed: false,\r\n");
      out.write("                href: \"");
      out.print(request.getContextPath());
      out.write("/train/department-dialog.do\",\r\n");
      out.write("                onClose:function(){  \r\n");
      out.write("                    $(this).dialog('destroy');  \r\n");
      out.write("                },\r\n");
      out.write("                onLoad:function(){\r\n");
      out.write("                \t$('#up_dept').textbox('setValue',selected.name);\r\n");
      out.write("                },\r\n");
      out.write("                buttons: [{\r\n");
      out.write("                    text: '确定',\r\n");
      out.write("                    iconCls: 'icon-ok',\r\n");
      out.write("                    handler: add\r\n");
      out.write("                }, {\r\n");
      out.write("                    text: '取消',\r\n");
      out.write("                    iconCls: 'icon-cancel',\r\n");
      out.write("                    handler: function () {\r\n");
      out.write("                        $('#dialog').dialog('destroy');                    \r\n");
      out.write("                    }\r\n");
      out.write("                }]\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 打开修改窗口\r\n");
      out.write("        */\r\n");
      out.write("        function openEdit(){\r\n");
      out.write("        \tvar item = $('#dg').datagrid('getSelected');\r\n");
      out.write("            if(!item){\r\n");
      out.write("                $.messager.alert('提醒','请选择需要修改的记录!');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("\t\t\t$('<div id=\"dialog\"></div>').dialog({\r\n");
      out.write("                title: \"修改信息\",\r\n");
      out.write("                width: 700,\r\n");
      out.write("                height: 400,\r\n");
      out.write("                modal:true,\r\n");
      out.write("                closed: false,\r\n");
      out.write("                href: \"");
      out.print(request.getContextPath());
      out.write("/train/department-dialog.do\",\r\n");
      out.write("                onClose:function(){  \r\n");
      out.write("                    $(this).dialog('destroy');  \r\n");
      out.write("                },\r\n");
      out.write("                onLoad:function(){\r\n");
      out.write("                \t$('#dept-form').form('load', item);\r\n");
      out.write("                },\r\n");
      out.write("                buttons: [{\r\n");
      out.write("                    text: '确定',\r\n");
      out.write("                    iconCls: 'icon-ok',\r\n");
      out.write("                    handler: edit\r\n");
      out.write("                }, {\r\n");
      out.write("                    text: '取消',\r\n");
      out.write("                    iconCls: 'icon-cancel',\r\n");
      out.write("                    handler: function () {\r\n");
      out.write("                        $('#dialog').dialog('destroy');                    \r\n");
      out.write("                    }\r\n");
      out.write("                }]\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function query(){\r\n");
      out.write("        \t$('#dg').datagrid('options').queryParams = {\r\n");
      out.write("            \tup_dept: $(\"#key-up-dept\").val(),\r\n");
      out.write("                depart_name: $(\"#key-dept\").val()\r\n");
      out.write("            };\r\n");
      out.write("            $('#dg').datagrid(\"reload\");\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function reset(){\r\n");
      out.write("            $(\"#key-up-dept\").textbox('setValue','');\r\n");
      out.write("            $(\"#key-dept\").textbox('setValue','');\r\n");
      out.write("            $('#dg').datagrid('options').queryParams = {};\r\n");
      out.write("            $('#dg').datagrid(\"reload\");           \r\n");
      out.write("        }\r\n");
      out.write("                \r\n");
      out.write("        $('#dg').datagrid({\r\n");
      out.write("            url:'sys/DepartmentList.do',\r\n");
      out.write("            method:'post',\r\n");
      out.write("\t        singleSelect:true,\r\n");
      out.write("\t        footer:'#ft',\r\n");
      out.write("\t        rownumbers:true,\r\n");
      out.write("\t        pageSize:20,           \r\n");
      out.write("\t        pagination:true,\r\n");
      out.write("\t        multiSort:true,\r\n");
      out.write("\t        fitColumns:false,\r\n");
      out.write("\t        fit:true,\r\n");
      out.write("\t        border:false,\r\n");
      out.write("\t        striped: true,\r\n");
      out.write("            frozenColumns:[[\r\n");
      out.write("\t\t        { field:'',width:100,align:'center',checkbox:true},\r\n");
      out.write("                { field:'depart_id',title:'单位编码',width:150,align:'center'}\r\n");
      out.write("\t\t    ]],\r\n");
      out.write("        \tcolumns:[[                \r\n");
      out.write("                { field:'depart_name',title:'单位名称',width:280,align:'center'},\r\n");
      out.write("                { field:'p_id',title:'上级单位编码',width:150,align:'center'},\r\n");
      out.write("                { field:'up_dept',title:'上级单位名称',width:250,align:'center'},\r\n");
      out.write("                { field:'idPayDeptName',title:'是否为付费单位',width:120,align:'center'}\r\n");
      out.write("            ]],\r\n");
      out.write("            toolbar: [{\r\n");
      out.write("\t            text: '添加', \r\n");
      out.write("\t            iconCls: 'icon-add', \r\n");
      out.write("\t            handler: openAdd\r\n");
      out.write("\t        }, '-', { \r\n");
      out.write("\t            text: '修改', \r\n");
      out.write("\t            iconCls: 'icon-edit', \r\n");
      out.write("\t            handler: openEdit\r\n");
      out.write("\t        }, '-',{ \r\n");
      out.write("\t            text: '删除', \r\n");
      out.write("\t            iconCls: 'icon-remove', \r\n");
      out.write("\t            handler: remove\r\n");
      out.write("\t        }]\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        /*\r\n");
      out.write("         * 左侧单位目录\r\n");
      out.write("         */\r\n");
      out.write("    \t$('#tt').tree({\r\n");
      out.write("\t\t\tonClick: function(node){\r\n");
      out.write("\t\t\t\t$(\"#key-up-dept\").val(node.id);\r\n");
      out.write("\t\t\t\tquery();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("    </script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
