/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2019-03-07 09:18:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.train.temp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class manilog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("        <div data-options=\"region:'north',split:false,collapsible:false,title:'条件查询'\" style=\"height:90px;\">\r\n");
      out.write("            <div style=\"margin:10px\">\r\n");
      out.write("                <label>类型：</label>\r\n");
      out.write("\t\t\t\t<select id=\"op_type\" class=\"easyui-combobox\" id=\"op_type\" style=\"width:120px;\">\r\n");
      out.write("\t\t\t\t    <option value=\"add\">新增</option>\r\n");
      out.write("\t\t\t\t    <option value=\"edit\">修改</option>\r\n");
      out.write("\t\t\t\t    <option value=\"remove\">删除</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("                <label>时间区间：</label>\r\n");
      out.write("\t\t\t\t<input class=\"easyui-datebox\" type=\"text\" id=\"startDate\" style=\"width:120px\">\r\n");
      out.write("\t\t\t\t--\r\n");
      out.write("\t\t\t\t<input class=\"easyui-datebox\" type=\"text\" id=\"endDate\" style=\"width:120px\">\r\n");
      out.write("                <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" onclick=\"query()\">查询</a>\r\n");
      out.write("                <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-undo\" onclick=\"reset()\">重置</a>\r\n");
      out.write("\t        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div data-options=\"region:'center'\">\r\n");
      out.write("        \t<table id=\"dg\" class=\"easyui-datagrid\"></table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        /*\r\n");
      out.write("        * 检索\r\n");
      out.write("        */\r\n");
      out.write("        function query(){\r\n");
      out.write("        \t$('#dg').datagrid('options').queryParams = {\r\n");
      out.write("            \top_type: $(\"#op_type\").val(),\r\n");
      out.write("\t\t        startDate: $(\"#startDate\").val(),\r\n");
      out.write("\t\t        endDate: $(\"#endDate\").val()\r\n");
      out.write("            };\r\n");
      out.write("            $('#dg').datagrid(\"reload\");  \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function reset(){\r\n");
      out.write("            $(\"#op_type\").textbox('setValue','');\r\n");
      out.write("\t\t    $(\"#startDate\").datebox('setValue','');\r\n");
      out.write("\t\t    $(\"#endDate\").datebox('setValue','');\r\n");
      out.write("            $('#dg').datagrid('options').queryParams = {};\r\n");
      out.write("            $('#dg').datagrid(\"reload\");           \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 载入数据\r\n");
      out.write("        */\r\n");
      out.write("        $('#dg').datagrid({\r\n");
      out.write("            url:'sys/logList.do',\r\n");
      out.write("            method:'post',\r\n");
      out.write("            singleSelect:true,\r\n");
      out.write("            footer:'#ft',\r\n");
      out.write("            rownumbers:true,\r\n");
      out.write("            pageSize:10,           \r\n");
      out.write("            pagination:true,\r\n");
      out.write("            multiSort:true,\r\n");
      out.write("            fitColumns:true,\r\n");
      out.write("            fit:true,\r\n");
      out.write("            border:false,\r\n");
      out.write("            striped: true,\r\n");
      out.write("            nowrap: false,\r\n");
      out.write("            columns:[[\r\n");
      out.write("                { field:'',width:50,align:'center',checkbox:true},\r\n");
      out.write("                { field:'tu_name',title:'操作人员',width:50,align:'center'},\r\n");
      out.write("                { field:'op_type',title:'日志类型',width:50,align:'center'},\r\n");
      out.write("                { field:'page_name',title:'功能页面',width:50,align:'center'},\r\n");
      out.write("                { field:'outline',title:'概要信息',width:80,align:'center'},\r\n");
      out.write("                { field:'content_d',title:'详细信息',width:300,align:'center'},\r\n");
      out.write("                { field:'gen_time',title:'日志创建时间',width:100,align:'center'}\r\n");
      out.write("            ]]\r\n");
      out.write("        });\r\n");
      out.write("    </script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
