/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2019-03-10 16:52:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.train.temp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pjxx_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/c.tld", Long.valueOf(1546843288000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<title>配件信息</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("        <div data-options=\"region:'north',split:false,collapsible:false,title:'条件查询'\" style=\"height:90px;\">\r\n");
      out.write("            <div style=\"margin:10px\">\r\n");
      out.write("                <label>名称：</label>\r\n");
      out.write(" \t\t\t\t<input class=\"easyui-textbox\" name=\"key-name\" id=\"key-name\">\r\n");
      out.write("                <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" onclick=\"query()\">查询</a>\r\n");
      out.write("                <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-undo\" onclick=\"reset()\">重置</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div data-options=\"region:'center'\">\r\n");
      out.write("        \t<table id=\"dg\" class=\"easyui-datagrid\"></table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\t     /**\r\n");
      out.write("\t     * Name 添加记录\r\n");
      out.write("\t     */\r\n");
      out.write("\t     function add(){\r\n");
      out.write("\t         $.ajax({\r\n");
      out.write("\t         \ttype: 'POST',\r\n");
      out.write("\t             url:'lj/insertLj.do',\r\n");
      out.write("\t             data: $('#pjxx-form').serialize(),\r\n");
      out.write("\t             dataType: \"json\",\r\n");
      out.write("\t             success:function(data){\r\n");
      out.write("\t                 var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("\t\t                if(data && 'Y' == data.state){\r\n");
      out.write("\t\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t\t                    $('#dialog').dialog('close');\r\n");
      out.write("\t\t                }else{\r\n");
      out.write("\t\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t                $('#dg').datagrid('reload');\r\n");
      out.write("\t             }\r\n");
      out.write("\t         })\r\n");
      out.write("\t     }\r\n");
      out.write("\t     \r\n");
      out.write("\t     /**\r\n");
      out.write("\t     * Name 修改记录\r\n");
      out.write("\t     */\r\n");
      out.write("\t     function edit(){\r\n");
      out.write("\t         $.ajax({\r\n");
      out.write("\t         \ttype: 'POST',\r\n");
      out.write("\t             url:'lj/updateLj.do',\r\n");
      out.write("\t             data: $('#pjxx-form').serialize(),\r\n");
      out.write("\t             dataType: \"json\",\r\n");
      out.write("\t             success:function(data){\r\n");
      out.write("\t                 var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("\t\t                if(data && 'Y' == data.state){\r\n");
      out.write("\t\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t\t                    $('#dialog').dialog('close');\r\n");
      out.write("\t\t                }else{\r\n");
      out.write("\t\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t                $('#dg').datagrid('reload');\r\n");
      out.write("\t             }\r\n");
      out.write("\t         })\r\n");
      out.write("\t     }\r\n");
      out.write("\t     \r\n");
      out.write("\t     /**\r\n");
      out.write("\t     * Name 删除记录\r\n");
      out.write("\t     */\r\n");
      out.write("\t     function remove(){\r\n");
      out.write("\t         var item = $('#dg').datagrid('getSelected');\r\n");
      out.write("\t         if(!item){\r\n");
      out.write("\t             $.messager.alert('提醒','请选择需要删除的记录!');\r\n");
      out.write("\t             return false;\r\n");
      out.write("\t         }\r\n");
      out.write("\t         $.messager.confirm('信息提示','确定要删除该记录？', function(result){\r\n");
      out.write("\t             if(result){\r\n");
      out.write("\t                 $.ajax({\r\n");
      out.write("\t                 \ttype: 'POST',\r\n");
      out.write("\t                     url:'lj/deleteLj.do',\r\n");
      out.write("\t                     data:{\r\n");
      out.write("\t                         id:item.id\r\n");
      out.write("\t                     },\r\n");
      out.write("\t                     dataType: \"json\",\r\n");
      out.write("\t                     success:function(data){\r\n");
      out.write("\t                         var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("\t                 \t\tif(data && 'Y' == data.state){\r\n");
      out.write("\t                     \t\t$.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                    \t\t\t$.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                 \t\t}\r\n");
      out.write("\t                 \t\t$('#dg').datagrid('reload');\r\n");
      out.write("\t                     }\t\r\n");
      out.write("\t                 });\r\n");
      out.write("\t             }\t\r\n");
      out.write("\t         });\r\n");
      out.write("\t     }\r\n");
      out.write("\t     \r\n");
      out.write("\t     /**\r\n");
      out.write("\t     * Name 打开添加窗口\r\n");
      out.write("\t     */\r\n");
      out.write("\t     function openAdd(){\r\n");
      out.write("\t         $('<div id=\"dialog\"></div>').dialog({\r\n");
      out.write("\t             title: \"添加信息\",\r\n");
      out.write("\t             width: 700,\r\n");
      out.write("\t             height: 400,\r\n");
      out.write("\t             modal:true,\r\n");
      out.write("\t             closed: false,\r\n");
      out.write("\t             href: \"train/pjxx-dialog.do\",\r\n");
      out.write("\t             onClose:function(){  \r\n");
      out.write("\t                 $(this).dialog('destroy');  \r\n");
      out.write("\t             },\r\n");
      out.write("\t             buttons: [{\r\n");
      out.write("\t                 text: '确定',\r\n");
      out.write("\t                 iconCls: 'icon-ok',\r\n");
      out.write("\t                 handler: add\r\n");
      out.write("\t             }, {\r\n");
      out.write("\t                 text: '取消',\r\n");
      out.write("\t                 iconCls: 'icon-cancel',\r\n");
      out.write("\t                 handler: function () {\r\n");
      out.write("\t                     $('#dialog').dialog('destroy');                    \r\n");
      out.write("\t                 }\r\n");
      out.write("\t             }]\r\n");
      out.write("\t         });\r\n");
      out.write("\t     }\r\n");
      out.write("\t     \r\n");
      out.write("\t     /**\r\n");
      out.write("\t     * Name 打开修改窗口\r\n");
      out.write("\t     */\r\n");
      out.write("\t     function openEdit(){\r\n");
      out.write("\t         var item = $('#dg').datagrid('getSelected');\r\n");
      out.write("\t         if(!item){\r\n");
      out.write("\t             $.messager.alert('提醒','请选择需要修改的记录!');\r\n");
      out.write("\t             return false;\r\n");
      out.write("\t         }\r\n");
      out.write("\t         \r\n");
      out.write("\t         $('<div id=\"dialog\"></div>').dialog({\r\n");
      out.write("\t             title: \"修改信息\",\r\n");
      out.write("\t             width: 700,\r\n");
      out.write("\t             height: 400,\r\n");
      out.write("\t             modal:true,\r\n");
      out.write("\t             closed: false,\r\n");
      out.write("\t             href: \"train/pjxx-dialog.do\",\r\n");
      out.write("\t             onClose:function(){  \r\n");
      out.write("\t                 $(this).dialog('destroy');  \r\n");
      out.write("\t             },\r\n");
      out.write("\t             onLoad:function(){\r\n");
      out.write("\t             \t$('#pjxx-form').form('load', item);\r\n");
      out.write("\t             },\r\n");
      out.write("\t             buttons: [{\r\n");
      out.write("\t                 text: '确定',\r\n");
      out.write("\t                 iconCls: 'icon-ok',\r\n");
      out.write("\t                 handler: edit\r\n");
      out.write("\t             }, {\r\n");
      out.write("\t                 text: '取消',\r\n");
      out.write("\t                 iconCls: 'icon-cancel',\r\n");
      out.write("\t                 handler: function () {\r\n");
      out.write("\t                     $('#dialog').dialog('destroy');                    \r\n");
      out.write("\t                 }\r\n");
      out.write("\t             }]\r\n");
      out.write("\t         });\r\n");
      out.write("\t     }\t\r\n");
      out.write("\t\r\n");
      out.write("\t     /*\r\n");
      out.write("\t     * 检索\r\n");
      out.write("\t     */\r\n");
      out.write("\t     function query(){\r\n");
      out.write("\t         $('#dg').datagrid('options').queryParams = {\r\n");
      out.write("\t             name: $(\"#key-name\").val()\r\n");
      out.write("\t         };\r\n");
      out.write("\t         $('#dg').datagrid(\"reload\");           \r\n");
      out.write("\t     }\r\n");
      out.write("\t     function reset(){\r\n");
      out.write("\t         $(\"#key-name\").textbox('setValue','');\r\n");
      out.write("\t         $('#dg').datagrid('options').queryParams = {};\r\n");
      out.write("\t         $('#dg').datagrid(\"reload\");           \r\n");
      out.write("\t     }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 载入数据\r\n");
      out.write("        */\r\n");
      out.write("        $('#dg').datagrid({\r\n");
      out.write("            url:'lj/queryLjList.do',\r\n");
      out.write("            method:'post',\r\n");
      out.write("            singleSelect:true,\r\n");
      out.write("            footer:'#ft',\r\n");
      out.write("            rownumbers:true,\r\n");
      out.write("            pageSize:50,           \r\n");
      out.write("            pagination:true,\r\n");
      out.write("            multiSort:false,\r\n");
      out.write("            fitColumns:false,\r\n");
      out.write("            fit:true,\r\n");
      out.write("            border:false,\r\n");
      out.write("            striped: true,\r\n");
      out.write("            frozenColumns:[[\r\n");
      out.write("\t\t        { field:'',width:100,align:'center',checkbox:true},\r\n");
      out.write("\t\t    ]],\r\n");
      out.write("            columns:[[\r\n");
      out.write("\t\t\t\t{ field:'code',title:'物料编号',sortable:true,width:150,align:'center'},\r\n");
      out.write("\t\t\t\t{ field:'name',title:'名称',sortable:true,width:100,align:'center'},\r\n");
      out.write("\t\t\t\t{ field:'price',title:'单价',sortable:true,width:100,align:'center'},\r\n");
      out.write("\t\t\t\t{ field:'amount',title:'数量',sortable:true,width:100,align:'center'},\r\n");
      out.write("                { field:'source_name',title:'货源',sortable:true,width:180,align:'center'},\r\n");
      out.write("                { field:'source_tel',title:'联系人及电话',sortable:true,width:180,align:'center'},\r\n");
      out.write("                { field:'remark',title:'备注',sortable:true,width:100,align:'center'},\r\n");
      out.write("            \t{ field:'inserttime',title:'插入日期',sortable:true,width:150,align:'center'},\r\n");
      out.write("            \t{ field:'updatetime',title:'更新日期',sortable:true,width:150,align:'center'},\r\n");
      out.write("            \t{ field:'operator',title:'操作人',sortable:true,width:100,align:'center'}\r\n");
      out.write("            ]],\r\n");
      out.write("            toolbar: [{\r\n");
      out.write("\t            text: '添加', \r\n");
      out.write("\t            iconCls: 'icon-add', \r\n");
      out.write("\t            handler: openAdd\r\n");
      out.write("\t        }, '-', {\r\n");
      out.write("\t            text: '修改', \r\n");
      out.write("\t            iconCls: 'icon-edit', \r\n");
      out.write("\t            handler: openEdit\r\n");
      out.write("\t        }, '-',{\r\n");
      out.write("\t            text: '删除', \r\n");
      out.write("\t            iconCls: 'icon-remove', \r\n");
      out.write("\t            handler: remove\r\n");
      out.write("\t        }]\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
