/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2019-03-09 09:30:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.train.temp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sbwxjl_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<title>设备维修记录</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.datagrid-cell, .datagrid-cell-group, .datagrid-header-rownumber, .datagrid-cell-rownumber{\r\n");
      out.write("\t\t\ttext-overflow: ellipsis;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("        <div data-options=\"region:'north',split:false,collapsible:false,title:'条件查询'\" style=\"height:90px;\">\r\n");
      out.write("            <div style=\"margin:10px\">\r\n");
      out.write("                <label>设备号：</label>\r\n");
      out.write(" \t\t\t\t<input class=\"easyui-textbox\" name=\"key-sw-id\" id=\"key-sw-id\">\r\n");
      out.write("                <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" onclick=\"query()\">查询</a>\r\n");
      out.write("                <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-undo\" onclick=\"reset()\">重置</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div data-options=\"region:'center'\">\r\n");
      out.write("        \t<table id=\"dg\" class=\"easyui-datagrid\"></table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        /**\r\n");
      out.write("        * Name 添加记录\r\n");
      out.write("        */\r\n");
      out.write("        function add(){\r\n");
      out.write("        \tif(!$(\"#sbwxjl-form\").form('enableValidation').form('validate')){\r\n");
      out.write("        \t\t$.messager.alert('信息提示',\"您有必填项目未填写，请填写完整！\",'info');\r\n");
      out.write("        \t\treturn false;\r\n");
      out.write("        \t}\r\n");
      out.write("            $.ajax({\r\n");
      out.write("            \ttype: 'POST',\r\n");
      out.write("                url:'equ/addSbwx.do',\r\n");
      out.write("                data: $('#sbwxjl-form').serialize(),\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                success:function(data){\r\n");
      out.write("                    var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("                    if(data && 'Y' == data.state){\r\n");
      out.write("                        $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                        $('#dialog').dialog('destroy');\r\n");
      out.write("                    }else{\r\n");
      out.write("                        $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                    }\r\n");
      out.write("                    $('#dg').datagrid('reload');\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 修改记录\r\n");
      out.write("        */\r\n");
      out.write("        function edit(){\r\n");
      out.write("        \tif(!$(\"#sbwxjl-form\").form('enableValidation').form('validate')){\r\n");
      out.write("        \t\t$.messager.alert('信息提示',\"您有必填项目未填写，请填写完整！\",'info');\r\n");
      out.write("        \t\treturn false;\r\n");
      out.write("        \t}\r\n");
      out.write("            $.ajax({\r\n");
      out.write("            \ttype: 'POST',\r\n");
      out.write("                url:'equ/updateSbwx.do',\r\n");
      out.write("                data: $('#sbwxjl-form').serialize(),\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                success:function(data){\r\n");
      out.write("                    var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("                    if(data && 'Y' == data.state){\r\n");
      out.write("                        $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                        $('#dialog').dialog('destroy');\r\n");
      out.write("                    }else{\r\n");
      out.write("                        $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                    }\r\n");
      out.write("                    $('#dg').datagrid('reload');\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 删除记录\r\n");
      out.write("        */\r\n");
      out.write("        function remove(){\r\n");
      out.write("            var items = $('#dg').datagrid('getChecked');\r\n");
      out.write("            var idsArray = [];\r\n");
      out.write("            if(items.length == 0){\r\n");
      out.write("                $.messager.alert('提醒','请选择需要删除的记录!');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            for(var i in items){\r\n");
      out.write("            \tidsArray.push(items[i].id)\r\n");
      out.write("            }\r\n");
      out.write("            $.messager.confirm('信息提示','确定要删除该记录？', function(result){\r\n");
      out.write("                if(result){\r\n");
      out.write("                    $.ajax({\r\n");
      out.write("                    \ttype: 'POST',\r\n");
      out.write("                        url:'equ/deleteSbwx.do',\r\n");
      out.write("                        data:{\r\n");
      out.write("                            ids:idsArray.join(\",\")\r\n");
      out.write("                        },\r\n");
      out.write("                        dataType: \"json\",\r\n");
      out.write("                        success:function(data){\r\n");
      out.write("                            var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("                    \t\tif(data && 'Y' == data.state){\r\n");
      out.write("                        \t\t$.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                    \t\t}else{\r\n");
      out.write("                       \t\t\t$.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                    \t\t}\r\n");
      out.write("                    \t\t$('#dg').datagrid('reload');\r\n");
      out.write("                        }\t\r\n");
      out.write("                    });\r\n");
      out.write("                }\t\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 打开添加窗口\r\n");
      out.write("        */\r\n");
      out.write("        function openAdd(){\r\n");
      out.write("            $('<div id=\"dialog\"></div>').dialog({\r\n");
      out.write("                title: \"添加信息\",\r\n");
      out.write("                width: 700,\r\n");
      out.write("                height: 450,\r\n");
      out.write("                modal:true,\r\n");
      out.write("                closed: false,\r\n");
      out.write("                href: \"train/sbwxjl-dialog.do\",\r\n");
      out.write("                onClose:function(){  \r\n");
      out.write("                    $(this).dialog('destroy');  \r\n");
      out.write("                },\r\n");
      out.write("                buttons: [{\r\n");
      out.write("                    text: '确定',\r\n");
      out.write("                    iconCls: 'icon-ok',\r\n");
      out.write("                    handler: add\r\n");
      out.write("                }, {\r\n");
      out.write("                    text: '取消',\r\n");
      out.write("                    iconCls: 'icon-cancel',\r\n");
      out.write("                    handler: function () {\r\n");
      out.write("                        $('#dialog').dialog('close');                    \r\n");
      out.write("                    }\r\n");
      out.write("                }]\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 打开修改窗口\r\n");
      out.write("        */\r\n");
      out.write("        function openEdit(){\r\n");
      out.write("            var items = $('#dg').datagrid('getChecked');\r\n");
      out.write("            if(items.length != 1){\r\n");
      out.write("                $.messager.alert('提醒','修改时必须且只能选中一条记录!');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            $('<div id=\"dialog\"></div>').dialog({\r\n");
      out.write("                title: \"修改信息\",\r\n");
      out.write("                width: 700,\r\n");
      out.write("                height: 450,\r\n");
      out.write("                modal:true,\r\n");
      out.write("                closed: false,\r\n");
      out.write("                href: \"train/sbwxjl-dialog.do\",\r\n");
      out.write("                onClose:function(){  \r\n");
      out.write("                    $(this).dialog('destroy');  \r\n");
      out.write("                },\r\n");
      out.write("                onLoad:function(){\r\n");
      out.write("                \t$('#sbwxjl-form').form('load', items[0]);\r\n");
      out.write("                \t\r\n");
      out.write("                \t$('#issue').combobox(\"setValue\",items[0].issue)\r\n");
      out.write("                },\r\n");
      out.write("                buttons: [{\r\n");
      out.write("                    text: '确定',\r\n");
      out.write("                    iconCls: 'icon-ok',\r\n");
      out.write("                    handler: edit\r\n");
      out.write("                }, {\r\n");
      out.write("                    text: '取消',\r\n");
      out.write("                    iconCls: 'icon-cancel',\r\n");
      out.write("                    handler: function () {\r\n");
      out.write("                        $('#dialog').dialog('close');                    \r\n");
      out.write("                    }\r\n");
      out.write("                }]\r\n");
      out.write("            });\r\n");
      out.write("        }\t\r\n");
      out.write("\r\n");
      out.write("        /*\r\n");
      out.write("        * 检索\r\n");
      out.write("        */\r\n");
      out.write("        function query(){\r\n");
      out.write("        \t$('#dg').datagrid('options').queryParams = {\r\n");
      out.write("        \t\tsw_id: $(\"#key-sw-id\").val()\r\n");
      out.write("            };\r\n");
      out.write("            $('#dg').datagrid(\"reload\");           \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 载入数据\r\n");
      out.write("        */\r\n");
      out.write("        $('#dg').datagrid({\r\n");
      out.write("            url:'equ/sbwxjlList.do',\r\n");
      out.write("            method:'post',\r\n");
      out.write("            singleSelect:false,\r\n");
      out.write("            footer:'#ft',\r\n");
      out.write("            rownumbers:true,\r\n");
      out.write("            pageSize:20,           \r\n");
      out.write("            pagination:true,\r\n");
      out.write("            multiSort:true,\r\n");
      out.write("            fitColumns:false,\r\n");
      out.write("            fit:true,\r\n");
      out.write("            border:false,\r\n");
      out.write("            striped: true,\r\n");
      out.write("            frozenColumns:[[\r\n");
      out.write("\t\t        { field:'',width:100,align:'center',checkbox:true},\r\n");
      out.write("                { field:'sw_id',title:'设备号',width:100,align:'center'}\r\n");
      out.write("\t\t    ]],\r\n");
      out.write("            columns:[[                \r\n");
      out.write("                { field:'devtype_name',title:'设备类型',width:100,align:'center'},\r\n");
      out.write("                { field:'mtype_name',title:'故障类型',width:100,align:'center'},\r\n");
      out.write("                { field:'issue',title:'故障现象',width:100,align:'center',\r\n");
      out.write("                \t                    formatter: function(value,row,index){\r\n");
      out.write("                \t\t                      return '<span title='+value+'>'+value+'</span>'  \r\n");
      out.write("                \t\t                    }},\r\n");
      out.write("                { field:'response',title:'现场反馈',width:100,align:'center'},\r\n");
      out.write("                { field:'mtime',title:'故障发生时间',width:150,align:'center'},\r\n");
      out.write("                { field:'issue_place',title:'故障发生地点',width:100,align:'center'},\r\n");
      out.write("                { field:'resolved',title:'解决方法',width:100,align:'center'},\r\n");
      out.write("                { field:'maintain_date',title:'送修日期',width:150,align:'center'},\r\n");
      out.write("                { field:'is_calibration',title:'是否标定',width:100,align:'center'},\r\n");
      out.write("                { field:'idpaydept',title:'是否收费',width:100,align:'center'},\r\n");
      out.write("                { field:'amount',title:'收费金额',width:100,align:'center'},\r\n");
      out.write("                { field:'manperson',title:'送修人',width:100,align:'center'},\r\n");
      out.write("                { field:'user_name',title:'填写人',width:100,align:'center'}                    \r\n");
      out.write("            ]],\r\n");
      out.write("            toolbar: [{\r\n");
      out.write("\t            text: '添加', \r\n");
      out.write("\t            iconCls: 'icon-add', \r\n");
      out.write("\t            handler: openAdd\r\n");
      out.write("\t        }, '-', { \r\n");
      out.write("\t            text: '修改', \r\n");
      out.write("\t            iconCls: 'icon-edit', \r\n");
      out.write("\t            handler: openEdit\r\n");
      out.write("\t        }, '-',{ \r\n");
      out.write("\t            text: '删除', \r\n");
      out.write("\t            iconCls: 'icon-remove', \r\n");
      out.write("\t            handler: remove\r\n");
      out.write("\t        }]\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        var issues=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gzjson}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
