/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2019-03-09 09:31:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.train.temp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sbzlxx_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<title>设备租赁信息</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("        <div data-options=\"region:'north',split:false,collapsible:false,title:'条件查询'\" style=\"height:90px;\">\r\n");
      out.write("            <div style=\"margin:10px\">\r\n");
      out.write("                <label>设备号：</label>\r\n");
      out.write(" \t\t\t\t<input class=\"easyui-textbox\" name=\"key-sw\" id=\"key-sw\">\r\n");
      out.write("                <label>租赁单位：</label>\r\n");
      out.write(" \t\t\t\t<input class=\"easyui-textbox\" name=\"key-dept\" id=\"key-dept\">\r\n");
      out.write("                <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" onclick=\"query()\">查询</a>\r\n");
      out.write("                <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-undo\" onclick=\"reset()\">重置</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div data-options=\"region:'center'\">\r\n");
      out.write("        \t<table id=\"dg\" class=\"easyui-datagrid\"></table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \t/**\r\n");
      out.write("        * Name 添加记录\r\n");
      out.write("        */\r\n");
      out.write("        function add(){\r\n");
      out.write("        \tif(!$(\"#sbzl-form\").form('enableValidation').form('validate')){\r\n");
      out.write("        \t\t$.messager.alert('信息提示',\"您有必填项目未填写，请填写完整！\",'info');\r\n");
      out.write("        \t\treturn false;\r\n");
      out.write("        \t}\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url:'");
      out.print(request.getContextPath());
      out.write("/equ/insertSbzl.do',\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                cache: false,\r\n");
      out.write("                data: new FormData($(\"#sbzl-form\")[0]),\r\n");
      out.write("                processData: false,\r\n");
      out.write("                contentType:false,\r\n");
      out.write("                async: false,\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                success: function (data) {\r\n");
      out.write("\t\t\t\t\tvar returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("\t                if(data && 'Y' == data.state){\r\n");
      out.write("\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                    $('#dialog').dialog('close');\r\n");
      out.write("\t                }else{\r\n");
      out.write("\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                }\r\n");
      out.write("\t                $('#dg').datagrid('reload');\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 修改记录\r\n");
      out.write("        */\r\n");
      out.write("        function edit(){\r\n");
      out.write("        \tif(!$(\"#sbzl-form\").form('enableValidation').form('validate')){\r\n");
      out.write("        \t\t$.messager.alert('信息提示',\"您有必填项目未填写，请填写完整！\",'info');\r\n");
      out.write("        \t\treturn false;\r\n");
      out.write("        \t}\r\n");
      out.write("            $.ajax({\r\n");
      out.write("            \ttype: 'POST',\r\n");
      out.write("            \tcache: false,\r\n");
      out.write("                url:'");
      out.print(request.getContextPath());
      out.write("/equ/updateSbzl.do',\r\n");
      out.write("                data: new FormData($(\"#sbzl-form\")[0]),\r\n");
      out.write("                processData: false,\r\n");
      out.write("                contentType:false,\r\n");
      out.write("                async: false,\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                success:function(data){\r\n");
      out.write("                    var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("\t                if(data && 'Y' == data.state){\r\n");
      out.write("\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                    $('#dialog').dialog('close');\r\n");
      out.write("\t                }else{\r\n");
      out.write("\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                }\r\n");
      out.write("\t                $('#dg').datagrid('reload');\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 删除记录\r\n");
      out.write("        */\r\n");
      out.write("        function remove(){\r\n");
      out.write("            var item = $('#dg').datagrid('getSelected');\r\n");
      out.write("            if(!item){\r\n");
      out.write("                $.messager.alert('提醒','请选择需要删除的记录!');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            $.messager.confirm('信息提示','确定要删除该记录？', function(result){\r\n");
      out.write("                if(result){\r\n");
      out.write("                    $.ajax({\r\n");
      out.write("                    \ttype: 'POST',\r\n");
      out.write("                        url:'");
      out.print(request.getContextPath());
      out.write("/equ/deleteSbzl.do',\r\n");
      out.write("                        data:{\r\n");
      out.write("                            id:item.id\r\n");
      out.write("                        },\r\n");
      out.write("                        dataType: \"json\",\r\n");
      out.write("                        success:function(data){\r\n");
      out.write("                            var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("                    \t\tif(data && 'Y' == data.state){\r\n");
      out.write("                        \t\t$.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                    \t\t}\r\n");
      out.write("                    \t\t$('#dg').datagrid('reload');\r\n");
      out.write("                        }\t\r\n");
      out.write("                    });\r\n");
      out.write("                }\t\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 打开添加窗口\r\n");
      out.write("        */\r\n");
      out.write("        function openAdd(){\r\n");
      out.write("            $('<div id=\"dialog\"></div>').dialog({\r\n");
      out.write("                title: \"添加信息\",\r\n");
      out.write("                width: 800,\r\n");
      out.write("                height: 500,\r\n");
      out.write("                modal:true,\r\n");
      out.write("                closed: false,\r\n");
      out.write("                href: \"");
      out.print(request.getContextPath());
      out.write("/train/sbzlxx-dialog.do\",\r\n");
      out.write("                onClose:function(){  \r\n");
      out.write("                    $(this).dialog('destroy');  \r\n");
      out.write("                },\r\n");
      out.write("                buttons: [{\r\n");
      out.write("                    text: '确定',\r\n");
      out.write("                    iconCls: 'icon-ok',\r\n");
      out.write("                    handler: add\r\n");
      out.write("                }, {\r\n");
      out.write("                    text: '取消',\r\n");
      out.write("                    iconCls: 'icon-cancel',\r\n");
      out.write("                    handler: function () {\r\n");
      out.write("                        $('#dialog').dialog('destroy');                    \r\n");
      out.write("                    }\r\n");
      out.write("                }]\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 打开修改窗口\r\n");
      out.write("        */\r\n");
      out.write("        function openEdit(){\r\n");
      out.write("            var item = $('#dg').datagrid('getSelected');\r\n");
      out.write("            if(!item){\r\n");
      out.write("                $.messager.alert('提醒','请选择需要修改的记录!');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            $('<div id=\"dialog\"></div>').dialog({\r\n");
      out.write("                title: \"修改信息\",\r\n");
      out.write("                width: 800,\r\n");
      out.write("                height: 500,\r\n");
      out.write("                modal:true,\r\n");
      out.write("                closed: false,\r\n");
      out.write("                href: \"");
      out.print(request.getContextPath());
      out.write("/train/sbzlxx-dialog.do\",\r\n");
      out.write("                onClose:function(){  \r\n");
      out.write("                    $(this).dialog('destroy');  \r\n");
      out.write("                },\r\n");
      out.write("                onLoad:function(){\r\n");
      out.write("                \tvar target={};\r\n");
      out.write("                \t$.each(item, function(key, val) {\r\n");
      out.write("                \t\tif(\"htsmj\"!=key && \"fpsmj\"!=key && \"djbsmj\"!=key){\r\n");
      out.write("    \t\t\t\t\t\ttarget[key]=val;                \t\t\r\n");
      out.write("                \t\t}\r\n");
      out.write("\t\t\t\t\t}); \r\n");
      out.write("                \t$('#sbzl-form').form('load', target);\r\n");
      out.write("                \t\r\n");
      out.write("                \tif(item.htsmj){\r\n");
      out.write("                \t\tcreateImg(\"ht-img\",item.htsmj);\r\n");
      out.write("                \t}\r\n");
      out.write("                \tif(item.fpsmj){\r\n");
      out.write("                \t\tcreateImg(\"fp-img\",item.fpsmj);\r\n");
      out.write("                \t}\r\n");
      out.write("                \tif(item.djbsmj){\r\n");
      out.write("                \t\tcreateImg(\"djbsmj-img\",item.djbsmj);\r\n");
      out.write("                \t}\r\n");
      out.write("                },\r\n");
      out.write("                buttons: [{\r\n");
      out.write("                    text: '确定',\r\n");
      out.write("                    iconCls: 'icon-ok',\r\n");
      out.write("                    handler: edit\r\n");
      out.write("                }, {\r\n");
      out.write("                    text: '取消',\r\n");
      out.write("                    iconCls: 'icon-cancel',\r\n");
      out.write("                    handler: function () {\r\n");
      out.write("                        $('#dialog').dialog('destroy');                    \r\n");
      out.write("                    }\r\n");
      out.write("                }]\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function createImg(boxId,src){\r\n");
      out.write("        \tvar imgBox = document.getElementById(boxId);\r\n");
      out.write("        \timgBox.innerHTML = \"<span>&times;</span><img id='\" + boxId + \"0'  />\";\r\n");
      out.write("        \tvar imgObjPreview = document.getElementById(boxId+0); \r\n");
      out.write("        \timgObjPreview.style.display = 'block';\r\n");
      out.write("            imgObjPreview.style.width = '50px';\r\n");
      out.write("            imgObjPreview.style.height = '50px';\r\n");
      out.write("            imgObjPreview.style.borderRadius = '3px';\r\n");
      out.write("            imgObjPreview.src = \"");
      out.print(request.getContextPath());
      out.write("/fileDownLoad.do?fileName=\"+src;\r\n");
      out.write("        }\r\n");
      out.write("        /*\r\n");
      out.write("        * 检索\r\n");
      out.write("        */\r\n");
      out.write("        function query(){\r\n");
      out.write("            $('#dg').datagrid('options').queryParams = {\r\n");
      out.write("            \tswinstrumentid: $(\"#key-sw\").val(),\r\n");
      out.write("                dept: $(\"#key-dept\").val()\r\n");
      out.write("            };\r\n");
      out.write("            $('#dg').datagrid(\"reload\");           \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function reset(){\r\n");
      out.write("        \t$(\"#key-sw\").textbox('setValue','');\r\n");
      out.write("            $(\"#key-dept\").textbox('setValue','');\r\n");
      out.write("            $('#dg').datagrid('options').queryParams = {};\r\n");
      out.write("            $('#dg').datagrid(\"reload\");           \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 载入数据\r\n");
      out.write("        */\r\n");
      out.write("        $('#dg').datagrid({\r\n");
      out.write("            url:'");
      out.print(request.getContextPath());
      out.write("/equ/querySbzlList.do',\r\n");
      out.write("            method:'post',\r\n");
      out.write("            singleSelect:true,\r\n");
      out.write("            footer:'#ft',\r\n");
      out.write("            rownumbers:true,\r\n");
      out.write("            pageSize:20,           \r\n");
      out.write("            pagination:true,\r\n");
      out.write("            multiSort:true,\r\n");
      out.write("            fitColumns:false,\r\n");
      out.write("            fit:true,\r\n");
      out.write("            border:false,\r\n");
      out.write("            striped: true,\r\n");
      out.write("            frozenColumns:[[\r\n");
      out.write("\t\t        { field:'',width:100,align:'center',checkbox:true},\r\n");
      out.write("                { field:'swinstrumentid',title:'设备号',width:100,align:'center'}\r\n");
      out.write("\t\t    ]],\r\n");
      out.write("            columns:[[\r\n");
      out.write("\t\t\t\t{ field:'zldw_mc',title:'租赁单位',width:100,align:'center'},\r\n");
      out.write("\t\t\t\t{ field:'qsrq',title:'租赁起始日期',width:150,align:'center'},\r\n");
      out.write("\t\t\t\t{ field:'zzrq',title:'租赁终止日期',width:150,align:'center'},\r\n");
      out.write("\t\t\t\t{ field:'htbh',title:'合同编号',width:100,align:'center'},\r\n");
      out.write("\t\t\t\t{ field:'dwlxr',title:'租赁单位单位联系人',width:150,align:'center'},\r\n");
      out.write("\t\t\t\t{ field:'lxdh',title:'联系电话',width:100,align:'center'},\r\n");
      out.write("\t\t\t\t{ field:'fysfjq',title:'费用是否结清',width:150,align:'center',formatter:formatOper2},\t\t\t\t\r\n");
      out.write("            \t{ field:'htsmj',title:'租赁合同扫描件',width:200,align:'center',formatter:formatOper1} ,\r\n");
      out.write("            \t{ field:'djbsmj',title:'租赁设备登记表扫描件',width:200,align:'center',formatter:formatOper1},\r\n");
      out.write("            \t{ field:'fpsmj',title:'发票扫描件',width:200,align:'center',formatter:formatOper1}\r\n");
      out.write("            ]],\r\n");
      out.write("            toolbar: [{\r\n");
      out.write("\t            text: '添加', \r\n");
      out.write("\t            iconCls: 'icon-add', \r\n");
      out.write("\t            handler: openAdd\r\n");
      out.write("\t        }, '-', { \r\n");
      out.write("\t            text: '修改', \r\n");
      out.write("\t            iconCls: 'icon-edit', \r\n");
      out.write("\t            handler: openEdit\r\n");
      out.write("\t        }, '-',{ \r\n");
      out.write("\t            text: '删除', \r\n");
      out.write("\t            iconCls: 'icon-remove', \r\n");
      out.write("\t            handler: remove\r\n");
      out.write("\t        }]\r\n");
      out.write("        });\r\n");
      out.write("        function formatOper1(val,row,index){\r\n");
      out.write("        \tif(val){\r\n");
      out.write("        \t\tvar url=encodeURI('");
      out.print(request.getContextPath());
      out.write("/fileDownLoad.do?fileName='+val);\r\n");
      out.write("        \t\treturn '<a href='+url+'><img style=\"width:20px;height:20px\" src='+url+'></a>';\r\n");
      out.write("        \t}\r\n");
      out.write("        }\r\n");
      out.write("        function formatOper2(val,row,index){\r\n");
      out.write("        \tif(val == \"0\"){\r\n");
      out.write("        \t\treturn '否';\r\n");
      out.write("        \t}else if(val == \"1\"){\r\n");
      out.write("        \t\treturn '是';\r\n");
      out.write("        \t}else{\r\n");
      out.write("        \t\treturn '';\r\n");
      out.write("        \t}\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
