/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2019-03-07 17:09:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.train.temp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sbzyxx_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/c.tld", Long.valueOf(1546843288000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<title>标定基准参数</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("        <div data-options=\"region:'north',split:false,collapsible:false,title:'条件查询'\" style=\"height:130px;\">\r\n");
      out.write("            <form id=\"searchForm\">\r\n");
      out.write("\t            <div style=\"margin:10px\">\r\n");
      out.write("\t\t                <label>小车序列号：</label>\r\n");
      out.write("\t\t \t\t\t\t<input class=\"easyui-textbox\" name=\"swinstrumentid\" id=\"key-xcxlh\"> \r\n");
      out.write("\t\t                <label>作业ID：</label>\r\n");
      out.write("\t\t \t\t\t\t<input class=\"easyui-textbox\" name=\"taskid\" id=\"key-zy\">\r\n");
      out.write("\t\t \t\t\t\t<label>工程名称：</label>\r\n");
      out.write("\t\t \t\t\t\t<input class=\"easyui-textbox\" name=\"project_name\" id=\"key-gc\">\r\n");
      out.write("\t\t \t\t\t\t<label>线路名称：</label>\r\n");
      out.write("\t\t \t\t\t\t<input class=\"easyui-textbox\" name=\"line_name\" id=\"key-xl\">\r\n");
      out.write("\t\t                <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" onclick=\"query()\">查询</a>\r\n");
      out.write("\t\t                <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-undo\" onclick=\"reset()\">重置</a>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div style=\"margin:10px\">\r\n");
      out.write("\t                <label>作业起始和结束时间：</label>\r\n");
      out.write("\t\t\t\t\t<input class=\"easyui-datetimebox\" type=\"text\" name=\"start_time\" id=\"key-start-time\" style=\"width:180px\">\r\n");
      out.write("\t\t\t\t\t--\r\n");
      out.write("\t\t\t\t\t<input class=\"easyui-datetimebox\" type=\"text\" name=\"end_time\" id=\"key-end-time\" style=\"width:180px\">\r\n");
      out.write("\t \t\t\t\t<label>是否有效：</label>\r\n");
      out.write("\t \t\t\t\t<select class=\"easyui-combobox\" name=\"sfyx_name\" id=\"key-sfyx\" data-options=\"editable:false\" style=\"width:120px\">\r\n");
      out.write("\t \t\t\t\t\t<option value=\"\">请选择</option>\r\n");
      out.write("\t \t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t \t\t\t\t</select>\r\n");
      out.write("\t            </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div data-options=\"region:'center'\">\r\n");
      out.write("        \t<table id=\"dg\" class=\"easyui-datagrid\"></table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        /*\r\n");
      out.write("        * 检索\r\n");
      out.write("        */\r\n");
      out.write("        function query(){\r\n");
      out.write("            $('#dg').datagrid('options').queryParams = {\r\n");
      out.write("            \tswinstrumentid: $(\"#key-xcxlh\").val(),\r\n");
      out.write("            \ttaskid: $(\"#key-zy\").val(),\r\n");
      out.write("                project_name: $(\"#key-gc\").val(),\r\n");
      out.write("                line_name: $(\"#key-xl\").val(),\r\n");
      out.write("                start_time: $(\"#key-start-time\").val(),\r\n");
      out.write("                end_time: $(\"#key-end-time\").val(),\r\n");
      out.write("                sfyx_name: $(\"#key-sfyx\").val()\r\n");
      out.write("            };\r\n");
      out.write("            $('#dg').datagrid(\"reload\");\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function reset(){\r\n");
      out.write("        \t$(\"#key-xcxlh\").textbox('setValue','');\r\n");
      out.write("        \t$(\"#key-zy\").textbox('setValue','');\r\n");
      out.write("            $(\"#key-gc\").textbox('setValue','');\r\n");
      out.write("            $(\"#key-xl\").textbox('setValue','');\r\n");
      out.write("            $(\"#key-start-time\").datetimebox('setValue','');\r\n");
      out.write("            $(\"#key-end-time\").datetimebox('setValue','');\r\n");
      out.write("            $(\"#key-sfyx\").textbox('setValue','');\r\n");
      out.write("            $('#dg').datagrid('options').queryParams = {};\r\n");
      out.write("            $('#dg').datagrid(\"reload\");\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 删除记录\r\n");
      out.write("        */\r\n");
      out.write("        function remove(){\r\n");
      out.write("            var item = $('#dg').datagrid('getSelected');\r\n");
      out.write("            if(!item){\r\n");
      out.write("                $.messager.alert('提醒','请选择需要删除的记录!');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            $.messager.confirm('信息提示','确定要删除该记录？', function(result){\r\n");
      out.write("                if(result){\r\n");
      out.write("                    $.ajax({\r\n");
      out.write("                    \ttype: 'POST',\r\n");
      out.write("                        url:'equ/deleteZy.do',\r\n");
      out.write("                        data:{\r\n");
      out.write("                            id: item.id\r\n");
      out.write("                        },\r\n");
      out.write("                        dataType: \"json\",\r\n");
      out.write("                        success:function(data){\r\n");
      out.write("                            var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("                    \t\tif(data && 'Y' == data.state){\r\n");
      out.write("                        \t\t$.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                    \t\t}else{\r\n");
      out.write("                       \t\t\t$.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                    \t\t}\r\n");
      out.write("                    \t\t$('#dg').datagrid('reload');\r\n");
      out.write("                        }\t\r\n");
      out.write("                    });\r\n");
      out.write("                }\t\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 载入数据\r\n");
      out.write("        */\r\n");
      out.write("        $('#dg').datagrid({\r\n");
      out.write("            url:'equ/zyList.do',\r\n");
      out.write("            method:'post',\r\n");
      out.write("            singleSelect:true,\r\n");
      out.write("            footer:'#ft',\r\n");
      out.write("            rownumbers:true,\r\n");
      out.write("            pageSize:50,           \r\n");
      out.write("            pagination:true,\r\n");
      out.write("            multiSort:false,\r\n");
      out.write("            fitColumns:false,\r\n");
      out.write("            fit:true,\r\n");
      out.write("            border:false,\r\n");
      out.write("            striped: false,\r\n");
      out.write("            queryParams: {\r\n");
      out.write("            \tid: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'\r\n");
      out.write("            },\r\n");
      out.write("            frozenColumns:[[\r\n");
      out.write("\t\t        { field:'',width:100,align:'center',checkbox:true},\r\n");
      out.write("                { field:'swinstrumentid',title:'小车序列号',sortable:true,width:100,align:'center'}\r\n");
      out.write("\t\t    ]],\r\n");
      out.write("\t\t    rowStyler: function(index,row){\r\n");
      out.write("\t\t\t\tif (row.sfyx_name == \"无效\"){\r\n");
      out.write("\t\t\t\t\treturn 'background-color:#ddd;';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("            columns:[[\r\n");
      out.write("\t\t\t\t{ field:'taskid',title:'作业ID',sortable:true,width:410,align:'center'},\r\n");
      out.write("\t\t\t\t{ field:'start_time',title:'作业起始时间',sortable:true,width:170,align:'center'},\r\n");
      out.write("\t\t\t\t{ field:'end_time',title:'作业结束时间',sortable:true,width:170,align:'center'},\r\n");
      out.write("\t\t\t\t{ field:'mileage',title:'作业长度',sortable:true,width:170,align:'center'},\r\n");
      out.write("                { field:'start_mileage',title:'起始里程',sortable:true,width:170,align:'center'},\r\n");
      out.write("                { field:'end_mileage',title:'终止里程',sortable:true,width:170,align:'center'},\r\n");
      out.write("            \t{ field:'xcbda',title:'现场标定A',sortable:true,width:100,align:'center'},\r\n");
      out.write("            \t{ field:'xcbdb',title:'现场标定B',sortable:true,width:100,align:'center'},\r\n");
      out.write("            \t{ field:'xcbdc',title:'现场标定C',sortable:true,width:100,align:'center'},\r\n");
      out.write("            \t{ field:'xcbdd',title:'现场标定D',sortable:true,width:100,align:'center'},\r\n");
      out.write("            \t{ field:'qjcgqfw',title:'单作业倾角传感器0的百分比',sortable:true,width:150,align:'center'},\r\n");
      out.write(" \r\n");
      out.write("            \t{ field:'wdcgqzxz',title:'作业温度传感器最小值',sortable:true,width:150,align:'center'},\r\n");
      out.write("            \t{ field:'wdcgqzdz',title:'作业温度传感器最大值',sortable:true,width:150,align:'center'},\r\n");
      out.write("            \t{ field:'bmq1',title:'编码器',sortable:true,width:100,align:'center'},\r\n");
      out.write("            \t{ field:'bmq2',title:'编码器',sortable:true,width:100,align:'center'},\r\n");
      out.write("            \t\r\n");
      out.write("            \t{ field:'ywcgq1',title:'左位移传感器状态',sortable:true,width:150,align:'center'},\r\n");
      out.write("            \t{ field:'ywcgq2',title:'右位移传感器状态',sortable:true,width:150,align:'center'},\r\n");
      out.write("                { field:'insert_time',title:'录入时间',sortable:true,width:170,align:'center'},\r\n");
      out.write("                { field:'update_time',title:'更新时间',sortable:true,width:170,align:'center'},\r\n");
      out.write("                { field:'bs',title:'计算次数',sortable:true,width:100,align:'center'},\r\n");
      out.write("                { field:'sfyx_name',title:'是否有效',sortable:true,width:100,align:'center'},\r\n");
      out.write("                { field:'ddd',title:'备注',width:100,align:'center'},\r\n");
      out.write("                { field:'wycgq',title:'位移传感器',sortable:true,width:150,align:'center'},\r\n");
      out.write("                { field:'wycgqp',title:'位移传感器P列',sortable:true,width:150,align:'center'},\r\n");
      out.write("                { field:'wycgqq',title:'位移传感器Q列 ',sortable:true,width:150,align:'center'},\r\n");
      out.write("                { field:'bczyhs',title:'本次作业的行数',sortable:true,width:150,align:'center'},\r\n");
      out.write("                { field:'eee',title:'操作',width:120,align:'center',formatter:formatOper}\r\n");
      out.write("            ]],\r\n");
      out.write("            toolbar: [{\r\n");
      out.write("\t            text: '删除',\r\n");
      out.write("\t            iconCls: 'icon-remove', \r\n");
      out.write("\t            handler: remove\r\n");
      out.write("\t        }, '-', { \r\n");
      out.write("\t            text: '下载', \r\n");
      out.write("\t            iconCls: 'icon-down', \r\n");
      out.write("\t            handler: downLoad\r\n");
      out.write("\t        }],\r\n");
      out.write("\t        onLoadSuccess: function(){\r\n");
      out.write("\t\t\t\t$('.sb').switchbutton({\r\n");
      out.write("            \t\tonChange: function(checked){\r\n");
      out.write("                \t\t$.ajax({\r\n");
      out.write("                \t\t\turl: '',\r\n");
      out.write("                \t\t\ttype: 'post',\r\n");
      out.write("                \t\t\tdata: {\r\n");
      out.write("                \t\t\t\tid: $(this).data(\"id\"),\r\n");
      out.write("                \t\t\t\tisChecked: checked\r\n");
      out.write("                \t\t\t},\r\n");
      out.write("                \t\t\terror: function (data) {\r\n");
      out.write("                    \t\t\talert(\"状态保存失败！\");\r\n");
      out.write("                \t\t\t}\r\n");
      out.write("                \t\t})\r\n");
      out.write("            \t\t}\r\n");
      out.write("        \t\t})\r\n");
      out.write("\t\t\t}\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        function formatOper(val,row,index){\r\n");
      out.write("        \tvar isChecked = row.isChecked?\"checked\":\"\";\r\n");
      out.write("        \treturn '<input class=\"sb\" data-id=\"'+row.id+'\" '+isChecked+' data-options=\"onText:\\'已处理\\',offText:\\'未处理\\'\" style=\"width:100px;height:30px\">';\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function downLoad(){\r\n");
      out.write("           window.location.href =\"equ/download_index.do?\"+$(\"#searchForm\").serialize();\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /train/temp/sbzyxx.jsp(35,7) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shifouyouxiao}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /train/temp/sbzyxx.jsp(35,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t        <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.dd_desc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.dd_value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fforEach_005f0_reused) {
        _jspx_th_c_005fforEach_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f0);
      }
    }
    return false;
  }
}
