/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2019-03-10 14:01:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.train.temp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sysparams_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("        <div data-options=\"region:'north',split:false,collapsible:false,title:'条件查询'\" style=\"height:90px;\">\r\n");
      out.write("        \t<div style=\"margin:10px\">\r\n");
      out.write("\t            <label>项目类型：</label><input id=\"key-type\" class=\"easyui-textbox\">\r\n");
      out.write("\t            <label>项目名称：</label><input id=\"key-name\" class=\"easyui-textbox\">\r\n");
      out.write("\t            <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" onclick=\"query()\">查询</a>\r\n");
      out.write("\t            <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-undo\" onclick=\"reset()\">重置</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div data-options=\"region:'center'\">\r\n");
      out.write("\t\t\t<table id=\"dg\" class=\"easyui-datagrid\"></table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        /**\r\n");
      out.write("        * Name 添加记录\r\n");
      out.write("        */\r\n");
      out.write("        function add(){\r\n");
      out.write("        \tif(!$(\"#dic-form\").form('enableValidation').form('validate')){\r\n");
      out.write("        \t\t$.messager.alert('信息提示',\"您有必填项目未填写，请填写完整！\",'info');\r\n");
      out.write("        \t\treturn false;\r\n");
      out.write("        \t}\r\n");
      out.write("            $.ajax({\r\n");
      out.write("            \ttype: 'POST',\r\n");
      out.write("                url:'sys/addDic.do',\r\n");
      out.write("                data: {\r\n");
      out.write("                \tdd_type_code:$(\"#dd_type_name\").combobox(\"getText\"),\r\n");
      out.write("                \tdd_type_name:$(\"#dd_type_name\").combobox(\"getValue\"),\r\n");
      out.write("                \tdd_value:$(\"#dd_value\").textbox(\"getValue\"),\r\n");
      out.write("                \tdd_desc:$(\"#dd_desc\").textbox(\"getValue\"),\r\n");
      out.write("                \tdd_status:$(\"#dd_status\").combobox(\"getValue\")\r\n");
      out.write("                },\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                success:function(data){\r\n");
      out.write("                    var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("\t                if(data && 'Y' == data.state){\r\n");
      out.write("\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                    $('#dialog').dialog('close');\r\n");
      out.write("\t                }else{\r\n");
      out.write("\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                }\r\n");
      out.write("\t                $('#dg').datagrid('reload');\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 修改记录\r\n");
      out.write("        */\r\n");
      out.write("        function edit(){\r\n");
      out.write("        \tif(!$(\"#dic-form\").form('enableValidation').form('validate')){\r\n");
      out.write("        \t\t$.messager.alert('信息提示',\"您有必填项目未填写，请填写完整！\",'info');\r\n");
      out.write("        \t\treturn false;\r\n");
      out.write("        \t}\r\n");
      out.write("            $.ajax({\r\n");
      out.write("            \ttype: 'POST',\r\n");
      out.write("                url:'sys/updateDic.do',\r\n");
      out.write("                data: {\r\n");
      out.write("                \tdd_type_code:$(\"#dd_type_name\").combobox(\"getText\"),\r\n");
      out.write("                \tdd_type_name:$(\"#dd_type_name\").combobox(\"getValue\"),\r\n");
      out.write("                \tdd_value:$(\"#dd_value\").textbox(\"getValue\"),\r\n");
      out.write("                \tdd_desc:$(\"#dd_desc\").textbox(\"getValue\"),\r\n");
      out.write("                \tdd_id:$('#dg').datagrid('getSelected').dd_id,\r\n");
      out.write("                \tdd_status:$(\"#dd_status\").combobox(\"getValue\")\r\n");
      out.write("                },\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                success:function(data){\r\n");
      out.write("                    var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("\t                if(data && 'Y' == data.state){\r\n");
      out.write("\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                    $('#dialog').dialog('close');\r\n");
      out.write("\t                }else{\r\n");
      out.write("\t                    $.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                }\r\n");
      out.write("\t                $('#dg').datagrid('reload');\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 删除记录\r\n");
      out.write("        */\r\n");
      out.write("        function remove(){\r\n");
      out.write("            var item = $('#dg').datagrid('getSelected');\r\n");
      out.write("            if(!item){\r\n");
      out.write("                $.messager.alert('提醒','请选择需要删除的记录!');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            $.messager.confirm('信息提示','确定要删除该记录？', function(result){\r\n");
      out.write("                if(result){\r\n");
      out.write("                    $.ajax({\r\n");
      out.write("                    \ttype: 'POST',\r\n");
      out.write("                        url:'sys/deleteDic.do',\r\n");
      out.write("                        data:{\r\n");
      out.write("                            dd_id: item.dd_id\r\n");
      out.write("                        },\r\n");
      out.write("                        dataType: \"json\",\r\n");
      out.write("                        success:function(data){\r\n");
      out.write("                            var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("\t                \t\tif(data && 'Y' == data.state){\r\n");
      out.write("\t                    \t\t$.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                \t\t}else{\r\n");
      out.write("\t                    \t\t$.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("\t                \t\t}\r\n");
      out.write("\t                \t\t$('#dg').datagrid('reload');\r\n");
      out.write("                        }\t\r\n");
      out.write("                    });\r\n");
      out.write("                }\t\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 打开添加窗口\r\n");
      out.write("        */\r\n");
      out.write("        function openAdd(){\r\n");
      out.write("        \t$(\"#dd_type_name\").combobox(\"enable\");\r\n");
      out.write("            $('<div id=\"dialog\"></div>').dialog({\r\n");
      out.write("                title: \"添加信息\",\r\n");
      out.write("                iconCls: 'icon-tim-add',\r\n");
      out.write("                width: 700,\r\n");
      out.write("                height: 400,\r\n");
      out.write("                modal:true,\r\n");
      out.write("                closed: false,\r\n");
      out.write("                href: \"train/sysparams-dialog.do\",\r\n");
      out.write("                onClose:function(){  \r\n");
      out.write("                    $(this).dialog('destroy');  \r\n");
      out.write("                },\r\n");
      out.write("                buttons: [{\r\n");
      out.write("                    text: '确定',\r\n");
      out.write("                    iconCls: 'icon-ok',\r\n");
      out.write("                    handler: add\r\n");
      out.write("                }, {\r\n");
      out.write("                    text: '取消',\r\n");
      out.write("                    iconCls: 'icon-cancel',\r\n");
      out.write("                    handler: function () {\r\n");
      out.write("                        $('#dialog').dialog('destroy');                  \r\n");
      out.write("                    }\r\n");
      out.write("                }]\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 打开修改窗口\r\n");
      out.write("        */\r\n");
      out.write("        function openEdit(){\r\n");
      out.write("        \t$(\"#dd_type_name\").combobox(\"disable\");\r\n");
      out.write("            var item = $('#dg').datagrid('getSelected');\r\n");
      out.write("            if(!item){\r\n");
      out.write("                $.messager.alert('提醒','请选择需要修改的记录!');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            $('<div id=\"dialog\"></div>').dialog({\r\n");
      out.write("                title: \"修改信息\",\r\n");
      out.write("                iconCls: 'icon-tim-add',\r\n");
      out.write("                width: 700,\r\n");
      out.write("                height: 400,\r\n");
      out.write("                modal:true,\r\n");
      out.write("                closed: false,\r\n");
      out.write("                href: \"train/sysparams-dialog.do\",\r\n");
      out.write("                onClose:function(){  \r\n");
      out.write("                    $(this).dialog('destroy');  \r\n");
      out.write("                },\r\n");
      out.write("                onLoad:function(){\r\n");
      out.write("                \t$('#dic-form').form('load', item);\r\n");
      out.write("                },\r\n");
      out.write("                buttons: [{\r\n");
      out.write("                    text: '确定',\r\n");
      out.write("                    iconCls: 'icon-ok',\r\n");
      out.write("                    handler: edit\r\n");
      out.write("                }, {\r\n");
      out.write("                    text: '取消',\r\n");
      out.write("                    iconCls: 'icon-cancel',\r\n");
      out.write("                    handler: function () {\r\n");
      out.write("                        $('#dialog').dialog('destroy');\r\n");
      out.write("                    }\r\n");
      out.write("                }]\r\n");
      out.write("            });\r\n");
      out.write("        }\t\r\n");
      out.write("\r\n");
      out.write("        /*\r\n");
      out.write("        * 检索\r\n");
      out.write("        */\r\n");
      out.write("        function query(){\r\n");
      out.write("        \t$('#dg').datagrid('options').queryParams = {\r\n");
      out.write("            \tdd_type_name: $(\"#key-type\").val(),\r\n");
      out.write("                dd_value: $(\"#key-name\").val()\r\n");
      out.write("            };\r\n");
      out.write("            $('#dg').datagrid(\"reload\");\r\n");
      out.write("        }\r\n");
      out.write("        function reset(){\r\n");
      out.write("            $(\"#key-type\").textbox('setValue','');\r\n");
      out.write("\t\t    $(\"#key-name\").textbox('setValue','');\r\n");
      out.write("            $('#dg').datagrid('options').queryParams = {};\r\n");
      out.write("            $('#dg').datagrid(\"reload\");\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        $('#dg').datagrid({\r\n");
      out.write("\t\t    title:'系统参数配置',\r\n");
      out.write("\t\t    rownumbers:true,\r\n");
      out.write("\t\t    pageSize:20,\r\n");
      out.write("\t\t    pagination:true,\r\n");
      out.write("\t\t    singleSelect:true,\t\t    \r\n");
      out.write("\t\t    remoteSort:false,\r\n");
      out.write("\t\t    border:false,\r\n");
      out.write("\t\t    fitColumns:true,\r\n");
      out.write("            fit:true,\r\n");
      out.write("            striped: true,\r\n");
      out.write("\t\t    url:'sys/dictionariesList.do',\r\n");
      out.write("\t\t    columns:[[\r\n");
      out.write("\t\t    \t{field:'',align:'center',checkbox:true},\r\n");
      out.write("\t\t        {field:'dd_type_name',title:'项目类型',width:'25%',align:'center'},\r\n");
      out.write("\t\t        {field:'dd_value',title:'项目名称',width:'25%',align:'right',align:'center'},\r\n");
      out.write("\t\t        {field:'dd_status',title:'项目状态',width:'25%',align:'right',align:'center'},\r\n");
      out.write("\t\t        {field:'dd_desc',title:'项目描述',width:'25%',align:'center'}\r\n");
      out.write("\t\t    ]],\r\n");
      out.write("\t\t    groupField:'dd_type_code',\r\n");
      out.write("\t\t    view: groupview,\r\n");
      out.write("\t\t    groupFormatter:function(value, rows){\r\n");
      out.write("\t\t        return value + '(' + rows.length + ')';\r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t    toolbar: [{ \r\n");
      out.write("\t            text: '添加', \r\n");
      out.write("\t            iconCls: 'icon-add', \r\n");
      out.write("\t            handler: openAdd\r\n");
      out.write("\t        }, '-', { \r\n");
      out.write("\t            text: '修改', \r\n");
      out.write("\t            iconCls: 'icon-edit', \r\n");
      out.write("\t            handler: openEdit\r\n");
      out.write("\t        }, '-',{ \r\n");
      out.write("\t            text: '删除', \r\n");
      out.write("\t            iconCls: 'icon-remove', \r\n");
      out.write("\t            handler: remove\r\n");
      out.write("\t        }],\r\n");
      out.write("            onLoadSuccess: function () {\r\n");
      out.write("                $('#dg').datagrid('collapseGroup');//默认分组折叠\r\n");
      out.write("            }\r\n");
      out.write("\t\t});\r\n");
      out.write("    </script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
