/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2019-03-18 19:00:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.train.temp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class xldlsj_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<title>线路断链数据</title>\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path;

      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("        <div data-options=\"region:'north',split:false,collapsible:false,title:'条件查询'\" style=\"height:90px;\">\r\n");
      out.write("            <div style=\"margin:10px\">\r\n");
      out.write("                <label>检测仪序列号：</label>\r\n");
      out.write(" \t\t\t\t<input class=\"easyui-textbox\" name=\"key-sw-id\" id=\"key-sw-id\">\r\n");
      out.write(" \t\t\t\t<label>记录状态：</label>\r\n");
      out.write(" \t\t\t\t<select class=\"easyui-combobox\" id=\"key-st\" data-options=\"editable:false\" style=\"width: 130px;\">\r\n");
      out.write("\t \t\t\t\t<option value=\"all\">全部</option>\r\n");
      out.write("\t \t\t\t\t<option value=\"0\" selected>最新记录</option>\r\n");
      out.write("\t \t\t\t\t<option value=\"1\">历史记录</option>\r\n");
      out.write("\t \t\t\t</select>\r\n");
      out.write("                <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" onclick=\"query()\">查询</a>\r\n");
      out.write("                <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-undo\" onclick=\"reset()\">重置</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div data-options=\"region:'center'\">\r\n");
      out.write("        \t<table id=\"dg\" class=\"easyui-datagrid\"></table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function uploadFile (){\r\n");
      out.write("        \t//获取上传文件控件内容\r\n");
      out.write("        \tvar file = $(\"#file\").filebox('files')[0];\r\n");
      out.write("        \t//判断控件中是否存在文件内容，如果不存在，弹出提示信息，阻止进一步操作\r\n");
      out.write("       \t\tif (file == null) { alert('错误，请选择文件'); return; }\r\n");
      out.write("        \t//获取文件名称\r\n");
      out.write("        \tvar fileName = file.name;\r\n");
      out.write("        \t//获取文件类型名称\r\n");
      out.write("        \tvar file_typename = fileName.substring(fileName.lastIndexOf('.'), fileName.length);\r\n");
      out.write("        \t//这里限定上传文件文件类型必须为.xlsx，如果文件类型不符，提示错误信息\r\n");
      out.write("        \tif (file_typename == '.xlsx'){\r\n");
      out.write("            \tvar formData = new FormData($(\"#sbbdjl-form\")[0]);\r\n");
      out.write("            \t$.ajax({\r\n");
      out.write("                \turl: \"");
      out.print(basePath);
      out.write("/equ/bdUpload.do\",\r\n");
      out.write("                \ttype: 'POST',\r\n");
      out.write("                \tdata: formData,\r\n");
      out.write("                \tcache: false,\r\n");
      out.write("                \tcontentType: false,\r\n");
      out.write("                \tprocessData: false,\r\n");
      out.write("                \tdataType: 'json',\r\n");
      out.write("                \tsuccess: function (data) {\r\n");
      out.write("                    \tvar returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("                    \tif(data && 'Y' == data.state){\r\n");
      out.write("                        \t$.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                        \t$('#dialog').dialog('destroy');\r\n");
      out.write("                    \t}else{\r\n");
      out.write("                       \t\t$.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                    \t}\r\n");
      out.write("                    \t$('#dg').datagrid('reload');\r\n");
      out.write("                \t},\r\n");
      out.write("                \terror: function (data) {\r\n");
      out.write("                    \talert(\"失败\");\r\n");
      out.write("                \t}\r\n");
      out.write("            \t});\r\n");
      out.write("        \t}else {\r\n");
      out.write("            \talert(\"文件类型错误\");\r\n");
      out.write("        \t}\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("        function openAdd(){\r\n");
      out.write("            $('<div id=\"dialog\"></div>').dialog({\r\n");
      out.write("                title: \"导入信息\",\r\n");
      out.write("                width: 600,\r\n");
      out.write("                height: 360,\r\n");
      out.write("                modal:true,\r\n");
      out.write("                closed: false,\r\n");
      out.write("                href: \"");
      out.print(basePath);
      out.write("/train/sbbdjl-dialog.do\",\r\n");
      out.write("                onClose:function(){  \r\n");
      out.write("                    $(this).dialog('destroy');  \r\n");
      out.write("                },\r\n");
      out.write("                buttons: [{\r\n");
      out.write("                    text: '上传',\r\n");
      out.write("                    iconCls: 'icon-ok',\r\n");
      out.write("                    handler: uploadFile\r\n");
      out.write("                }, {\r\n");
      out.write("                    text: '取消',\r\n");
      out.write("                    iconCls: 'icon-cancel',\r\n");
      out.write("                    handler: function () {\r\n");
      out.write("                        $('#dialog').dialog('close');                    \r\n");
      out.write("                    }\r\n");
      out.write("                }]\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        /**\r\n");
      out.write("        * Name 删除记录\r\n");
      out.write("        */\r\n");
      out.write("        function remove(){\r\n");
      out.write("            var item = $('#dg').datagrid('getSelected');\r\n");
      out.write("            if(!item){\r\n");
      out.write("                $.messager.alert('提醒','请选择需要删除的记录!');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            $.messager.confirm('信息提示','确定要删除该记录？', function(result){\r\n");
      out.write("                if(result){\r\n");
      out.write("                    $.ajax({\r\n");
      out.write("                    \ttype: 'POST',\r\n");
      out.write("                        url:'");
      out.print(basePath);
      out.write("/equ/deleteoutBd.do',\r\n");
      out.write("                        data:{\r\n");
      out.write("                            id:item.id\r\n");
      out.write("                        },\r\n");
      out.write("                        dataType: \"json\",\r\n");
      out.write("                        success:function(data){\r\n");
      out.write("                            var returnMsg = data.returnMsg?data.returnMsg:\"提交失败\";\r\n");
      out.write("                    \t\tif(data && 'Y' == data.state){\r\n");
      out.write("                        \t\t$.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                    \t\t}else{\r\n");
      out.write("                       \t\t\t$.messager.alert('信息提示',returnMsg,'info');\r\n");
      out.write("                    \t\t}\r\n");
      out.write("                    \t\t$('#dg').datagrid('reload');\r\n");
      out.write("                        }\t\r\n");
      out.write("                    });\r\n");
      out.write("                }\t\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function downLoad(){\r\n");
      out.write("        \twindow.location.href='");
      out.print(basePath);
      out.write("/upLoad/SIWEI智能轨道检测仪出厂标定表模板.xlsx';\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /*\r\n");
      out.write("        * 检索\r\n");
      out.write("        */\r\n");
      out.write("        function query(){\r\n");
      out.write("        \t$('#dg').datagrid('options').queryParams = {\r\n");
      out.write("        \t\tsw_id: $(\"#key-sw-id\").val(),\r\n");
      out.write("        \t\tzxjl: $(\"#key-st\").combobox(\"getValue\")\r\n");
      out.write("            };\r\n");
      out.write("            $('#dg').datagrid(\"reload\"); \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("         function reset(){\r\n");
      out.write("         \t$(\"#key-st\").combobox(\"setValue\",\"\");\r\n");
      out.write("        \t$('#dg').datagrid('options').queryParams = {};\r\n");
      out.write("            $('#dg').datagrid(\"reload\"); \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("        * Name 载入数据\r\n");
      out.write("        */\r\n");
      out.write("        $('#dg').datagrid({\r\n");
      out.write("            url:'equ/outBdList.do',\r\n");
      out.write("            method:'post',\r\n");
      out.write("            singleSelect:true,\r\n");
      out.write("            footer:'#ft',\r\n");
      out.write("            rownumbers:true,\r\n");
      out.write("            pageSize:20,           \r\n");
      out.write("            pagination:true,\r\n");
      out.write("            multiSort:true,\r\n");
      out.write("            fitColumns:true,\r\n");
      out.write("            fit:true,\r\n");
      out.write("            border:false,\r\n");
      out.write("            striped: true,\r\n");
      out.write("            frozenColumns:[[\r\n");
      out.write("\t\t        { field:'',width:100,align:'center',checkbox:true}\r\n");
      out.write("\t\t    ]],\r\n");
      out.write("            columns:[[\r\n");
      out.write("                { field:'dsy',title:'贯通里程',width:100,align:'center'},\r\n");
      out.write("                { field:'dsy',title:'现场里程',width:100,align:'center'},\r\n");
      out.write("                { field:'dsy',title:'断链里程',width:100,align:'center'},\r\n");
      out.write("                { field:'dsy',title:'断链差值',width:100,align:'center'},\r\n");
      out.write("                { field:'dsy',title:'差值累加',width:100,align:'center'},\r\n");
      out.write("                { field:'dsy',title:'备注',width:100,align:'center'}\r\n");
      out.write("            ]],\r\n");
      out.write("            toolbar: [{ \r\n");
      out.write("\t            text: '导入', \r\n");
      out.write("\t            iconCls: 'icon-add', \r\n");
      out.write("\t            handler: openAdd\r\n");
      out.write("\t        }, '-', { \r\n");
      out.write("\t            text: '删除', \r\n");
      out.write("\t            iconCls: 'icon-remove', \r\n");
      out.write("\t            handler: remove\r\n");
      out.write("\t        }, '-', { \r\n");
      out.write("\t            text: '模板下载', \r\n");
      out.write("\t            iconCls: 'icon-down', \r\n");
      out.write("\t            handler: downLoad\r\n");
      out.write("\t        }]\r\n");
      out.write("        });\r\n");
      out.write("        function formatOper(val,row,index){\r\n");
      out.write("        \tvar url=encodeURI(\"");
      out.print(basePath);
      out.write("\"+row.url);\r\n");
      out.write("        \treturn '<a href='+url+' class=\"easyui-linkbutton l-btn l-btn-small\"><span class=\"l-btn-left\"><span class=\"l-btn-text\">下载文件</span></span></a> '\r\n");
      out.write("        \t\t\t+'<a href=\"#\" class=\"easyui-linkbutton l-btn l-btn-small\"><span class=\"l-btn-left\"><span class=\"l-btn-text\" onclick=\"goBdDetail('+row.id+')\">查询详情</span></span></a>';\r\n");
      out.write("        }\r\n");
      out.write("        function goBdDetail(id){\r\n");
      out.write("\t\t\t$('<div id=\"dialog\"></div>').dialog({\r\n");
      out.write("\t\t\t\ttitle: '详情',\r\n");
      out.write("                width: '90%',\r\n");
      out.write("                height: '90%',\r\n");
      out.write("                modal:true,\r\n");
      out.write("                closed: false,\r\n");
      out.write("                href: \"train/bdDetail.do?id=\"+id,\r\n");
      out.write("                onClose:function(){  \r\n");
      out.write("                    $(this).dialog('destroy');  \r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
