/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-03-24 05:56:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.workflow;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.aegon_cnooc.framework.db.ConnectionPool;
import com.aegon_cnooc.oa.workflow.WFEngine;
import java.sql.Connection;
import com.aegon_cnooc.oa.constants.Constants;
import com.aegon_cnooc.oa.ibatis.to.TuOafUsersTO;
import com.aegon_cnooc.util.StringUtil;

public final class view_005ftask_005fprocess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=gbk");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String viewtype = (String)request.getAttribute("viewtype");
String taskid  = (String)request.getAttribute("taskid");
String cur_nodeid  = (String)request.getAttribute("cur_nodeid");

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t\t<title>查看</title>\r\n");
      out.write("\t\t<link href=\"");
      out.print(path);
      out.write("/css/reset.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<link href=\"");
      out.print(path);
      out.write("/css/styles.css\" rel=\"stylesheet\"\r\n");
      out.write("\t\t\ttype=\"text/css\" />\r\n");
      out.write("\t\t<script src=\"");
      out.print(path);
      out.write("/js/jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.print(path);
      out.write("/js/treeview.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {background:#E4F4FD;}\r\n");
      out.write("html{overflow:scroll; overflow-y:auto;overflow-x:hidden;}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" >\r\n");
      out.write("function paginationQuery(e){\r\n");
      out.write(" var genstepname = document.getElementById('genstepname');\r\n");
      out.write(" var prcname = document.getElementById('prcname');\r\n");
      out.write(" var user_name = document.getElementById('user_name');\r\n");
      out.write(" \r\n");
      out.write(" var rectimeStart = document.getElementById('rectimeStart');\r\n");
      out.write(" var rectimeEnd = document.getElementById('rectimeEnd');\r\n");
      out.write(" var proctimeStart = document.getElementById('proctimeStart');\r\n");
      out.write(" var proctimeEnd = document.getElementById('proctimeEnd');\r\n");
      out.write(" var linkQuery = document.getElementById('linkQuery');\r\n");
      out.write(" document.forms[0].current_page.value=e;\r\n");
      out.write(" document.forms[0].submit();\r\n");
      out.write(" //e.href = e.href+\"&genstepname=\"+genstepname.value+\"&prcname=\"+prcname.value+\"&user_name=\"+user_name.value+\"&rectimeStart=\"+rectimeStart.value+\"&rectimeEnd=\"+rectimeEnd.value+\"&proctimeStart=\"+proctimeStart.value+\"&proctimeEnd=\"+proctimeEnd.value;\r\n");
      out.write("}\r\n");
      out.write("function backtask(taskid,PROCID,bak_nodeid,cur_nodeid,back_userid,wfid){\r\n");
      out.write("    if(document.forms[0].comments.value==\"\"){\r\n");
      out.write("    \talert(\"必须录入退回原因\");\r\n");
      out.write("    \tdocument.forms[0].comments.focus();\r\n");
      out.write("    \treturn;\r\n");
      out.write("    }\r\n");
      out.write("\tdocument.forms[0].action = \"");
      out.print(path );
      out.write("/workflow/backTask.do?taskid=\"+taskid+\"&PROCID=\"+PROCID+\"&bak_nodeid=\"+bak_nodeid+\"&cur_nodeid=\"+cur_nodeid+\"&back_userid=\"+back_userid+\"&wfid=\"+wfid;\r\n");
      out.write("\tdocument.forms[0].submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<form action=\"");
      out.print(path);
      out.write("/workflow/viewTaskProcess.do\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"current_page\" value=\"1\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"taskid\" value=\"");
      out.print(taskid );
      out.write("\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"viewtype\" value=\"");
      out.print(viewtype );
      out.write("\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"cur_nodeid\" value=\"");
      out.print(cur_nodeid );
      out.write("\"/>\r\n");
      out.write("\t\t<div id=\"right\">\r\n");
      out.write("\t\t\t<div id=\"right_conter\">\r\n");
      out.write("\t\t\t<!--  \r\n");
      out.write("\t\t\t\t<p class=\"login\">\r\n");
      out.write("\t\t\t\t\t登录用户：allen 部门：IT 区域：上海 2011年7月2日 星期五\r\n");
      out.write("\t\t\t\t\t<input name=\"\" type=\"button\" class=\"btn\" value=\"退出系统\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t-->\r\n");
      out.write("\t\t\t\t");

					List list = (List)request.getAttribute("list");
					Map queryMap = (Map)request.getAttribute("queryMap");
					
					int current_page = Integer.parseInt((String)request.getAttribute("current_page"));
					int totalRow = Integer.parseInt((String)request.getAttribute("totalRow"));
					int page_size = Integer.parseInt((String)request.getAttribute("page_size"));
					int totalPage = Integer.parseInt((String)request.getAttribute("totalPage"));
				 
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"inqure\">\r\n");
      out.write("\t\t\t\t\t<input name=\"\" type=\"button\" class=\"btn3\" value=\"高级搜索\" style=\"display: none;\"/>\r\n");
      out.write("\t\t\t\t\t<input name=\"\" type=\"button\" class=\"btn2\" value=\"查询\" style=\"display:none\"/>\r\n");
      out.write("\t\t\t\t\t<input name=\"\" type=\"text\" style=\"width:126px; display: none;\"  class=\"btn4\" />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<table style=\"border: 1px;width: 100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"padding-left: 10px;\">处理节点</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input size=\"15\" id=\"genstepname\" name=\"genstepname\" value=\"");
      out.print(queryMap.get("genstepname") );
      out.write("\"/> </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>动作</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input size=\"15\" id=\"prcname\" name=\"prcname\" value=\"");
      out.print(queryMap.get("prcname") );
      out.write("\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>处理者</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input size=\"15\" id=\"user_name\" name=\"user_name\" value=\"");
      out.print(queryMap.get("user_name") );
      out.write("\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>到达时间</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input size=\"10\" id=\"rectimeStart\" name=\"rectimeStart\" value=\"");
      out.print(queryMap.get("rectimeStart") );
      out.write("\" />-<input size=\"10\" id=\"rectimeEnd\" name=\"rectimeEnd\" value=\"");
      out.print(queryMap.get("rectimeEnd") );
      out.write("\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>处理时间</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input size=\"10\" id=\"proctimeStart\" name=\"proctimeStart\" value=\"");
      out.print(queryMap.get("proctimeStart") );
      out.write("\"/>-<input size=\"10\" id=\"proctimeEnd\" name=\"proctimeEnd\" value=\"");
      out.print(queryMap.get("proctimeEnd") );
      out.write("\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn2\" value=\"查询\" />\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"con_box\">\r\n");
      out.write("\t\t\t\t\t<table border=\"0\" align=\"left\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th width=\"5%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"\" type=\"checkbox\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th  width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t处理节点\r\n");
      out.write("\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th  width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t到达时间\r\n");
      out.write("\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t处理时间\r\n");
      out.write("\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th width=\"5%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t处理者\r\n");
      out.write("\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t动作\r\n");
      out.write("\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t");

							for(int i=0;i<list.size();i++){
							Map map = (Map)list.get(i);
							 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstep ");
      out.print(i+1+(current_page-1)*page_size );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(map.get("genstepname") );
      out.write("&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(map.get("rectime") );
      out.write("&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(StringUtil.getNulToBlank(map.get("proctime")) );
      out.write("&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(map.get("user_name") );
      out.write("&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(map.get("proctime")==null?"待处理":map.get("prcname") );
      out.write("&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
if("backTask".equals(viewtype)){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" onclick=\"backtask('");
      out.print(taskid );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(map.get("PROCID") );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(map.get("nodeid") );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(cur_nodeid );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(map.get("userid") );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(map.get("wfid") );
      out.write("')\">退回到此节点</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"7\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t退回原因：<textarea rows=\"5\" cols=\"120\" name=\"comments\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"zi\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t共");
      out.print(totalRow );
      out.write("条记录 第");
      out.print(current_page );
      out.write('/');
      out.print(totalPage );
      out.write("页 每页 ");
      out.print(page_size );
      out.write(" 条记录 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a onclick=\"paginationQuery('1')\" href=\"#\">第一页</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a onclick=\"paginationQuery(");
      out.print((current_page-1==0?1:current_page-1) );
      out.write(")\" href=\"#\">上一页</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a onclick=\"paginationQuery(");
      out.print((current_page+1>totalPage?totalPage:current_page+1) );
      out.write(")\" href=\"#\">下一页</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a onclick=\"paginationQuery(");
      out.print(totalPage );
      out.write(")\" href=\"#\">最后一页</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"");
      out.print(path );
      out.write("/images/button3.gif\" style=\"display:none;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resultMessage }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
