/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-03-24 05:45:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.frontend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.aegon_cnooc.oa.ibatis.to.TuOafUsersTO;
import com.aegon_cnooc.oa.constants.Constants;

public final class left_005fwf_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/struts-logic.tld", Long.valueOf(1490334066985L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fname_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005fid;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fname_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fname_005fid.release();
    _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005fid.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;

    java.lang.Object _jspx_wf_1 = null;

    try {
      response.setContentType("text/html;charset=gbk");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");

String path = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>同方全球人寿IT内部管理系统</title>\r\n");
      out.write("<link href=\"");
      out.print(path );
      out.write("/css/reset.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.print(path );
      out.write("/css/styles.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"");
      out.print(path );
      out.write("/js/jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path );
      out.write("/js/treeview.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("html{overflow:scroll;overflow-y:auto;overflow-x:hidden;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");

TuOafUsersTO user = (TuOafUsersTO)session.getAttribute(Constants.GLOBAL_SESSION_USER);
//+v2.0 add ITMS00065 suqiang 2014-02-27 start
String isOutSource=(String)session.getAttribute("isOutSource");  //是否外包供应商 0 or 1
String isSupplierPM = (String)session.getAttribute("isSupplierPM");	//是否供应商PM 0 or 1
String pSMD = (String)session.getAttribute("pSMD");	//是否PM SA ITD_Manager ITD_Director  Y or N
//+v2.0 add ITMS00065 suqiang 2014-02-27 end
 
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background:#E4F4FD;padding:0;padding:0;\">\r\n");
      out.write("<div id=\"left\">\r\n");
      out.write("  <div class=\"xbjys\" >\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"left_navtit\">\r\n");
      out.write("      <!--\r\n");
      out.write("      <h3 class=\"menu_22 menu_2 menu_bg\"><em>行政部门流程</em></h3>\r\n");
      out.write("      <div class=\"menu_3\">\r\n");
      out.write("        <div class=\"left_tit current\">\r\n");
      out.write("          <h4>办公用品申请</h4>\r\n");
      out.write("          <div class=\"left_list\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">礼品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">访客申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">印刷申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">办公用品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"left_tit\">\r\n");
      out.write("          <h4>办公用品申请1</h4>\r\n");
      out.write("          <div class=\"left_list accordionContent\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">礼品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">访客申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">印刷申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">办公用品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"left_tit\">\r\n");
      out.write("          <h4>办公用品申请2</h4>\r\n");
      out.write("          <div class=\"left_list accordionContent\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">礼品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">访客申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">印刷申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">办公用品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("    <div class=\"left_navtit\">\r\n");
      out.write("      <h3 class=\"menu_22\"><em>法务部门流程</em></h3>\r\n");
      out.write("      <div class=\"menu_3 accordionContent\">\r\n");
      out.write("        <div class=\"left_tit current\">\r\n");
      out.write("          <h4>办公用品申请</h4>\r\n");
      out.write("          <div class=\"left_list\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">礼品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">访客申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">印刷申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">办公用品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"left_navtit\">\r\n");
      out.write("      <h3 class=\"menu_22\"><em>营运部门流程</em></h3>\r\n");
      out.write("      <div class=\"menu_3 accordionContent\">\r\n");
      out.write("        <div class=\"left_tit current\">\r\n");
      out.write("          <h4>办公用品申请</h4>\r\n");
      out.write("          <div class=\"left_list\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">礼品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">访客申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">印刷申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">办公用品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"left_navtit\">\r\n");
      out.write("      <h3 class=\"menu_22\"><em>法务部门流程</em></h3>\r\n");
      out.write("      <div class=\"menu_3 accordionContent\">\r\n");
      out.write("        <div class=\"left_tit current\">\r\n");
      out.write("          <h4>办公用品申请</h4>\r\n");
      out.write("          <div class=\"left_list\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">礼品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">访客申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">印刷申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">办公用品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"left_navtit\">\r\n");
      out.write("      <h3 class=\"menu_22\"><em>HR部门流程</em></h3>\r\n");
      out.write("      <div class=\"menu_3 accordionContent\">\r\n");
      out.write("        <div class=\"left_tit current\">\r\n");
      out.write("          <h4>功能列表</h4>\r\n");
      out.write("          <div class=\"left_list\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">礼品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">访客申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">印刷申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">办公用品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("-->\r\n");
      //  logic:iterate
      org.apache.struts.taglib.logic.IterateTag _jspx_th_logic_005fiterate_005f0 = (org.apache.struts.taglib.logic.IterateTag) _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fname_005fid.get(org.apache.struts.taglib.logic.IterateTag.class);
      boolean _jspx_th_logic_005fiterate_005f0_reused = false;
      try {
        _jspx_th_logic_005fiterate_005f0.setPageContext(_jspx_page_context);
        _jspx_th_logic_005fiterate_005f0.setParent(null);
        // /frontend/left_wf.jsp(154,0) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_logic_005fiterate_005f0.setId("wfCat");
        // /frontend/left_wf.jsp(154,0) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_logic_005fiterate_005f0.setName("wfList");
        int _jspx_eval_logic_005fiterate_005f0 = _jspx_th_logic_005fiterate_005f0.doStartTag();
        if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          java.lang.Object wfCat = null;
          if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.pushBody();
            _jspx_th_logic_005fiterate_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
            _jspx_th_logic_005fiterate_005f0.doInitBody();
          }
          wfCat = (java.lang.Object) _jspx_page_context.findAttribute("wfCat");
          do {
            out.write("\r\n");
            out.write("    <div class=\"left_navtit\">\r\n");
            out.write("      <h3 class=\"menu_22\"><em>");
            if (_jspx_meth_bean_005fwrite_005f0(_jspx_th_logic_005fiterate_005f0, _jspx_page_context))
              return;
            out.write("</em></h3>\r\n");
            out.write("      <div class=\"menu_3 accordionContent\">\r\n");
            out.write("        <div class=\"left_tit current\">\r\n");
            out.write("          <h4>功能列表</h4>\r\n");
            out.write("          <div class=\"left_list\">\r\n");
            out.write("            <ul>\r\n");
            out.write("            <!-- +v2.0 add ITMS00065 suqiang 2014-02-27 start -->\r\n");
            out.write("            ");
            //  c:if
            org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
            boolean _jspx_th_c_005fif_005f0_reused = false;
            try {
              _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
              // /frontend/left_wf.jsp(163,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'0'==isOutSource ||'0'!=isSupplierPM  }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
              int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
              if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("            <!-- +v2.0 add ITMS00065 suqiang 2014-02-27 start -->\r\n");
                  out.write("            ");
                  //  logic:iterate
                  org.apache.struts.taglib.logic.IterateTag _jspx_th_logic_005fiterate_005f1 = (org.apache.struts.taglib.logic.IterateTag) _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005fid.get(org.apache.struts.taglib.logic.IterateTag.class);
                  boolean _jspx_th_logic_005fiterate_005f1_reused = false;
                  try {
                    _jspx_th_logic_005fiterate_005f1.setPageContext(_jspx_page_context);
                    _jspx_th_logic_005fiterate_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
                    // /frontend/left_wf.jsp(165,12) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_logic_005fiterate_005f1.setId("wf");
                    // /frontend/left_wf.jsp(165,12) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_logic_005fiterate_005f1.setName("wfCat");
                    // /frontend/left_wf.jsp(165,12) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_logic_005fiterate_005f1.setProperty("wflist");
                    int _jspx_eval_logic_005fiterate_005f1 = _jspx_th_logic_005fiterate_005f1.doStartTag();
                    if (_jspx_eval_logic_005fiterate_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                      java.lang.Object wf = null;
                      if (_jspx_eval_logic_005fiterate_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                        out = _jspx_page_context.pushBody();
                        _jspx_th_logic_005fiterate_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
                        _jspx_th_logic_005fiterate_005f1.doInitBody();
                      }
                      wf = (java.lang.Object) _jspx_page_context.findAttribute("wf");
                      do {
                        out.write("\r\n");
                        out.write("              ");
                        //  c:if
                        org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
                        boolean _jspx_th_c_005fif_005f1_reused = false;
                        try {
                          _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
                          _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f1);
                          // /frontend/left_wf.jsp(166,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wf.wfid=='502' && pSMD=='Y'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
                          int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
                          if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            do {
                              out.write("\r\n");
                              out.write("        \t\t<li><a href=\"");
                              out.print(path );
                              out.write("/workflow/newWFFormOnload.do?wfid=");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wf.wfid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
                              out.write("&type=Post\" target=\"main_content\">");
                              if (_jspx_meth_bean_005fwrite_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
                              return;
                              out.write("</a></li>\r\n");
                              out.write("        \t  ");
                              int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                          }
                          if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                          _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
                          _jspx_th_c_005fif_005f1_reused = true;
                        } finally {
                          if (!_jspx_th_c_005fif_005f1_reused) {
                            _jspx_th_c_005fif_005f1.release();
                            _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f1);
                          }
                        }
                        out.write("\r\n");
                        out.write("              ");
                        //  c:if
                        org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
                        boolean _jspx_th_c_005fif_005f2_reused = false;
                        try {
                          _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
                          _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f1);
                          // /frontend/left_wf.jsp(169,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wf.wfid!='502' && isSupplierPM=='0'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
                          int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
                          if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            do {
                              out.write("\r\n");
                              out.write("        \t\t<li><a href=\"");
                              out.print(path );
                              out.write("/workflow/newWFFormOnload.do?wfid=");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wf.wfid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
                              out.write("&type=Post\" target=\"main_content\">");
                              if (_jspx_meth_bean_005fwrite_005f2(_jspx_th_c_005fif_005f2, _jspx_page_context))
                              return;
                              out.write("</a></li>\r\n");
                              out.write("              ");
                              int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                          }
                          if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                          _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
                          _jspx_th_c_005fif_005f2_reused = true;
                        } finally {
                          if (!_jspx_th_c_005fif_005f2_reused) {
                            _jspx_th_c_005fif_005f2.release();
                            _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f2);
                          }
                        }
                        out.write("\r\n");
                        out.write("            ");
                        int evalDoAfterBody = _jspx_th_logic_005fiterate_005f1.doAfterBody();
                        wf = (java.lang.Object) _jspx_page_context.findAttribute("wf");
                        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                          break;
                      } while (true);
                      if (_jspx_eval_logic_005fiterate_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                        out = _jspx_page_context.popBody();
                      }
                    }
                    if (_jspx_th_logic_005fiterate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005fid.reuse(_jspx_th_logic_005fiterate_005f1);
                    _jspx_th_logic_005fiterate_005f1_reused = true;
                  } finally {
                    if (!_jspx_th_logic_005fiterate_005f1_reused) {
                      _jspx_th_logic_005fiterate_005f1.release();
                      _jsp_getInstanceManager().destroyInstance(_jspx_th_logic_005fiterate_005f1);
                    }
                  }
                  out.write("\r\n");
                  out.write("            <!-- +v2.0 add ITMS00065 suqiang 2014-02-27 start -->                       \r\n");
                  out.write("            ");
                  int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
              _jspx_th_c_005fif_005f0_reused = true;
            } finally {
              if (!_jspx_th_c_005fif_005f0_reused) {
                _jspx_th_c_005fif_005f0.release();
                _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f0);
              }
            }
            out.write("\r\n");
            out.write("            <!-- +v2.0 add ITMS00065 suqiang 2014-02-27 start -->\r\n");
            out.write("            </ul>\r\n");
            out.write("          </div>\r\n");
            out.write("        </div>\r\n");
            out.write("      </div>\r\n");
            out.write("    </div>\r\n");
            out.write("    ");
            int evalDoAfterBody = _jspx_th_logic_005fiterate_005f0.doAfterBody();
            wfCat = (java.lang.Object) _jspx_page_context.findAttribute("wfCat");
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_logic_005fiterate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fname_005fid.reuse(_jspx_th_logic_005fiterate_005f0);
        _jspx_th_logic_005fiterate_005f0_reused = true;
      } finally {
        if (!_jspx_th_logic_005fiterate_005f0_reused) {
          _jspx_th_logic_005fiterate_005f0.release();
          _jsp_getInstanceManager().destroyInstance(_jspx_th_logic_005fiterate_005f0);
        }
      }
      out.write("\r\n");
      out.write("    <!--  \r\n");
      out.write("    <div class=\"left_navtit\">\r\n");
      out.write("      <h3 class=\"menu_22\"><em>IT部门流程</em></h3>\r\n");
      out.write("      <div class=\"menu_3 current\">\r\n");
      out.write("        <div class=\"left_tit current\">\r\n");
      out.write("          <h4>功能列表</h4>\r\n");
      out.write("          <div class=\"left_list\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"");
      out.print(path );
      out.write("/workflow/newWFFormOnload.do?wfid=153&type=Post\" target=\"main_content\">需求管理流程</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(path );
      out.write("/workflow/newWFFormOnload.do?wfid=901&type=Post\"  target=\"main_content\">缺陷管理流程</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(path );
      out.write("/workflow/newWFFormOnload.do?wfid=159&type=Post\"  target=\"main_content\">数据维护流程</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(path );
      out.write("/workflow/newWFFormOnload.do?wfid=145&type=Post\"  target=\"main_content\">上线管理流程</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    -->\r\n");
      out.write("<!--  \r\n");
      out.write("    <div class=\"left_navtit\" >\r\n");
      out.write("      <h3 class=\"menu_22\"><em>流程演示demo</em></h3>\r\n");
      out.write("      <div class=\"menu_3 accordionContent\">\r\n");
      out.write("        <div class=\"left_tit current\">\r\n");
      out.write("          <h4>流程列表</h4>\r\n");
      out.write("          <div class=\"left_list\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"");
      out.print(path );
      out.write("/workflow/newDemoWFOnload.do?wfid=9999&type=Post\"   target=\"main_content\">演示流程</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    -->\r\n");
      out.write("    <!--\r\n");
      out.write("    <div class=\"left_navtit\"  >\r\n");
      out.write("      <h3 class=\"menu_22\"><em>业务部门流程</em></h3>\r\n");
      out.write("      <div class=\"menu_3 accordionContent\">\r\n");
      out.write("        <div class=\"left_tit current\">\r\n");
      out.write("          <h4>办公用品申请</h4>\r\n");
      out.write("          <div class=\"left_list\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">礼品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">访客申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">印刷申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">办公用品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"left_navtit\" >\r\n");
      out.write("      <h3 class=\"menu_22\"><em>其他</em></h3>\r\n");
      out.write("      <div class=\"menu_3 accordionContent\">\r\n");
      out.write("        <div class=\"left_tit current\">\r\n");
      out.write("          <h4>办公用品申请</h4>\r\n");
      out.write("          <div class=\"left_list\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">礼品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">访客申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">印刷申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">办公用品申请</a></li>\r\n");
      out.write("              <li><a href=\"#\">名片申请</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t-->\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_bean_005fwrite_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:write
    org.apache.struts.taglib.bean.WriteTag _jspx_th_bean_005fwrite_005f0 = (org.apache.struts.taglib.bean.WriteTag) _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.get(org.apache.struts.taglib.bean.WriteTag.class);
    boolean _jspx_th_bean_005fwrite_005f0_reused = false;
    try {
      _jspx_th_bean_005fwrite_005f0.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fwrite_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
      // /frontend/left_wf.jsp(156,30) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f0.setName("wfCat");
      // /frontend/left_wf.jsp(156,30) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f0.setProperty("wfcatname");
      int _jspx_eval_bean_005fwrite_005f0 = _jspx_th_bean_005fwrite_005f0.doStartTag();
      if (_jspx_th_bean_005fwrite_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_bean_005fwrite_005f0);
      _jspx_th_bean_005fwrite_005f0_reused = true;
    } finally {
      if (!_jspx_th_bean_005fwrite_005f0_reused) {
        _jspx_th_bean_005fwrite_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_bean_005fwrite_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fwrite_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:write
    org.apache.struts.taglib.bean.WriteTag _jspx_th_bean_005fwrite_005f1 = (org.apache.struts.taglib.bean.WriteTag) _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.get(org.apache.struts.taglib.bean.WriteTag.class);
    boolean _jspx_th_bean_005fwrite_005f1_reused = false;
    try {
      _jspx_th_bean_005fwrite_005f1.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fwrite_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /frontend/left_wf.jsp(167,112) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f1.setName("wf");
      // /frontend/left_wf.jsp(167,112) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f1.setProperty("wfname");
      int _jspx_eval_bean_005fwrite_005f1 = _jspx_th_bean_005fwrite_005f1.doStartTag();
      if (_jspx_th_bean_005fwrite_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_bean_005fwrite_005f1);
      _jspx_th_bean_005fwrite_005f1_reused = true;
    } finally {
      if (!_jspx_th_bean_005fwrite_005f1_reused) {
        _jspx_th_bean_005fwrite_005f1.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_bean_005fwrite_005f1);
      }
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fwrite_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:write
    org.apache.struts.taglib.bean.WriteTag _jspx_th_bean_005fwrite_005f2 = (org.apache.struts.taglib.bean.WriteTag) _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.get(org.apache.struts.taglib.bean.WriteTag.class);
    boolean _jspx_th_bean_005fwrite_005f2_reused = false;
    try {
      _jspx_th_bean_005fwrite_005f2.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fwrite_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /frontend/left_wf.jsp(170,112) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f2.setName("wf");
      // /frontend/left_wf.jsp(170,112) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f2.setProperty("wfname");
      int _jspx_eval_bean_005fwrite_005f2 = _jspx_th_bean_005fwrite_005f2.doStartTag();
      if (_jspx_th_bean_005fwrite_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_bean_005fwrite_005f2);
      _jspx_th_bean_005fwrite_005f2_reused = true;
    } finally {
      if (!_jspx_th_bean_005fwrite_005f2_reused) {
        _jspx_th_bean_005fwrite_005f2.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_bean_005fwrite_005f2);
      }
    }
    return false;
  }
}
