/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-03-24 05:45:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.frontend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.aegon_cnooc.oa.ibatis.to.TuOafUsersTO;
import com.aegon_cnooc.oa.constants.Constants;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=gbk");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();

TuOafUsersTO user = (TuOafUsersTO)session.getAttribute(Constants.GLOBAL_SESSION_USER);
String dept = user.getDept();
String isOutSource=(String)session.getAttribute("isOutSource");
//+v2.0 add ITMS00065 suqiang 2014-02-27 start
String isSupplierPM = (String)session.getAttribute("isSupplierPM");
//+v2.0 add ITMS00065 suqiang 2014-02-27 end

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\r\n");
      out.write("<title>同方全球人寿IT内部管理系统</title>\r\n");
      out.write("<link href=\"");
      out.print(path );
      out.write("/css/reset.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.print(path );
      out.write("/css/styles.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"");
      out.print(path );
      out.write("/js/jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path );
      out.write("/js/menu_select.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("<div class=\"logo\"><em class=\"f-yh\">");
      if (_jspx_meth_bean_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</em></div>\r\n");
      out.write("<div class=\"topnav\">\r\n");
      out.write("<span class=\"nav-l\"><img src=\"");
      out.print(path );
      out.write("/images/nav-l.jpg\" /></span>\r\n");
      out.write("<ul class=\"t_news_tit\" >\r\n");
      out.write("<li><a href=\"");
      out.print(path );
      out.write("/frontend/taskOnload.do\"  target=\"main\" class=\"f-yh current\" ><em >首页</em></a></li>\r\n");

if("BPR".equals(dept) ||"IT".equals(dept)||"Actuarial".equals(dept)||"Actuary and Business Development".equals(dept)||"Product Development".equals(dept)){
//if("BPR".equals(dept) ||"IT".equals(dept)){

      out.write("\r\n");
      out.write("<li><a href=\"");
      out.print(path );
      out.write("/frontend/forms_all.jsp\" class=\"f-yh \" target=\"main\"><em>工作日志</em></a></li>\r\n");
} 
      out.write('\r');
      out.write('\n');
if("0".equals(isOutSource) || !"0".equals(isSupplierPM)) {
      out.write("\r\n");
      out.write("<li><a href=\"");
      out.print(path );
      out.write("/frontend/forms_wf.jsp\" class=\"f-yh\" target=\"main\"><em>各种表单</em></a></li>\r\n");
} 
      out.write("\r\n");
      out.write("<li><a href=\"");
      out.print(path );
      out.write("/frontend/forms_todo.jsp\" class=\"f-yh\" target=\"main\"><em>待处理任务</em></a></li>\r\n");
      out.write("<li><a href=\"");
      out.print(path );
      out.write("/frontend/forms_cc.jsp\" class=\"f-yh\" target=\"main\"><em>CC任务</em></a></li>\r\n");
      out.write("<li><a href=\"");
      out.print(path );
      out.write("/frontend/forms_self.jsp\" class=\"f-yh\" target=\"main\"><em>我发起的</em></a></li>\r\n");
      out.write("<li><a href=\"");
      out.print(path );
      out.write("/frontend/forms_rela.jsp\" class=\"f-yh\" target=\"main\"><em>我参与的</em></a></li>\r\n");
      out.write("<li><a href=\"");
      out.print(path );
      out.write("/frontend/report.jsp\" class=\"f-yh\" target=\"main\"><em>查询统计</em></a></li>\r\n");
      out.write("<li><a href=\"");
      out.print(path );
      out.write("/frontend/signOut.do\" class=\"f-yh\" target=\"_parent\"><em>【退出】</em></a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("<span class=\"nav-r\"><img src=\"");
      out.print(path );
      out.write("/images/nav-r.jpg\" /></span>\r\n");
      out.write("</div>  \r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_bean_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f0 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    boolean _jspx_th_bean_005fmessage_005f0_reused = false;
    try {
      _jspx_th_bean_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fmessage_005f0.setParent(null);
      // /frontend/top.jsp(27,35) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fmessage_005f0.setKey("OA_AEGONCNOOC.TITLE");
      int _jspx_eval_bean_005fmessage_005f0 = _jspx_th_bean_005fmessage_005f0.doStartTag();
      if (_jspx_th_bean_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f0);
      _jspx_th_bean_005fmessage_005f0_reused = true;
    } finally {
      if (!_jspx_th_bean_005fmessage_005f0_reused) {
        _jspx_th_bean_005fmessage_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_bean_005fmessage_005f0);
      }
    }
    return false;
  }
}
