/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-03-21 05:25:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class page_005fadmin_005forgan_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=gbk");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write(" <head>\r\n");
      out.write("<title>组织架构定义</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path );
      out.write("/css/jquery_easyui/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path );
      out.write("/css/jquery_easyui/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path );
      out.write("/js/jquery_easyui/jquery-1.4.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path );
      out.write("/js/jquery_easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path );
      out.write("/css/page_table1.css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function() {\r\n");
      out.write("\t\tvar upd_flg = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${upd_flg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\tvar add_branch_id = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${add_branch_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\tvar add_branch_name = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${add_branch_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\tif((upd_flg == null) || (upd_flg == \"\")) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar leafText = \"<a href=\\\"");
      out.print(path);
      out.write("/admin/organOnload.do?organ_id=\";\r\n");
      out.write("\t\tleafText = leafText + add_branch_id;\r\n");
      out.write("\t\tleafText = leafText + \"\\\"\";\r\n");
      out.write("\t\tleafText = leafText + \" target=\\\"content_frame\\\">\";\r\n");
      out.write("\t\tleafText = leafText + add_branch_name;\r\n");
      out.write("\t\tleafText = leafText + \"</a>\";\r\n");
      out.write("\t\tif(upd_flg == \"1\") {\r\n");
      out.write("\t\t\t//新增\r\n");
      out.write("\t\t\tself.parent.appendBranch(leafText);\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(upd_flg == \"2\") {\r\n");
      out.write("\t\t\t//修改\r\n");
      out.write("\t\t\tself.parent.updateCompanyOrBranch(leafText);\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function btn_submit_grouptypesetting()\r\n");
      out.write("{\r\n");
      out.write("window.location.href=\"");
      out.print(path);
      out.write("/admin/groupTypeSettingOnload.do\"; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function btn_submit_leadertypesetting()\r\n");
      out.write("{\r\n");
      out.write("window.location.href=\"");
      out.print(path);
      out.write("/admin/leaderTypeSettingOnload.do\"; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function btn_submit_addsubgrop()\r\n");
      out.write("{\r\n");
      out.write("window.location.href=\"");
      out.print(path );
      out.write("/admin/newOrganOnload.do?organName=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organTreeTO.organ_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&organId=\"+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("; \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function btn_submit_addDeptTree(){\r\n");
      out.write("window.location.href=\"");
      out.print(path);
      out.write("/admin/newDeptTreeOnload.do?organId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function confirmWindow(msg) {\r\n");
      out.write("   return window.confirm(msg);\r\n");
      out.write(" }\r\n");
      out.write("function btn_submit_deletegrouptype()\r\n");
      out.write("{\r\n");
      out.write(" var msg = \"确认要删除记录吗?\";\r\n");
      out.write(" if(!confirmWindow(msg)){\r\n");
      out.write("    return;\r\n");
      out.write(" }\r\n");
      out.write("  $.ajax({\r\n");
      out.write("  type:\"POST\",\r\n");
      out.write("  url: \"checkChilOrgan.do\",\r\n");
      out.write("  data: \"organId=\"+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(",\r\n");
      out.write("  dataType:\"json\",\r\n");
      out.write("  success: function(data){\r\n");
      out.write("  if(data>0){\r\n");
      out.write("  alert('该组织下存在下级组织，请先删除下级组织门在删除该组织！');\r\n");
      out.write("  return;\r\n");
      out.write("  }else{\r\n");
      out.write("  window.location.href=\"");
      out.print(path );
      out.write("/admin/deleteOrgan.do?lcu=\"+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${GLOBAL_SESSION_USER.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("+\"&organId=\"+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("; \r\n");
      out.write("  }\r\n");
      out.write("  }\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function btn_submit_addLeaders()\r\n");
      out.write("{\r\n");
      out.write("window.location.href=\"");
      out.print(path);
      out.write("/admin/addLeaderOnload.do\"; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function btn_submit_addLeader()\r\n");
      out.write("{\r\n");
      out.write("window.location.href=\"");
      out.print(path);
      out.write("/admin/addLeaderOnload.do?organId=\"+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function get_employ_Json(){\t\t         \r\n");
      out.write("  var employeeJson=\"\\\"{\\\"employees\\\":[\";\r\n");
      out.write("var employee=document.getElementById(\"right_\");\r\n");
      out.write("for(var i=0;i<employee.length;i++){\r\n");
      out.write(" employeeJson=employeeJson+\"{\\\"user_id\\\":\\\"\"+employee.options[i].value+\"\\\",\\\"user_name\\\":\\\"\"+employee.options[i].text+\"\\\"},\";   \r\n");
      out.write("}\r\n");
      out.write("var end=employeeJson.length-1;\r\n");
      out.write("var Json=employeeJson.substring(1,end) ;\r\n");
      out.write("   Json=Json+\"]}\";\r\n");
      out.write("//window.location.href=\"");
      out.print(path);
      out.write("/admin/updateEmployeeState.do?employeeJson=\"+Json;\r\n");
      out.write("return Json;\r\n");
      out.write("}\r\n");
      out.write("function input_check(){\r\n");
      out.write("if($(\"#groupName\").val()==\"\"){\r\n");
      out.write("alert(\"请输入名称！\");\r\n");
      out.write("$(\"#groupName\").focus();\r\n");
      out.write("    return false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if($('#groupName').val().length>100){\r\n");
      out.write("alert(\"您输入的组织的名称过长，请重新输入！\");\r\n");
      out.write("$(\"#groupName\").focus();\r\n");
      out.write("return false;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("return true;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function btn_submit_save()\r\n");
      out.write("{\r\n");
      out.write("if(input_check()){\r\n");
      out.write("document.forms[0].action=\"");
      out.print(path);
      out.write("/admin/updateEmployeeState.do?employeeJson=\"+get_employ_Json();\r\n");
      out.write("document.forms[0].submit();\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("function right_move()\r\n");
      out.write("{\r\n");
      out.write("\tvar con_data=[];\r\n");
      out.write("\tfor(var i=0;i<document.getElementById(\"left_\").length;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(document.getElementById(\"left_\").options[i].selected)\r\n");
      out.write("\t\t\tcon_data[con_data.length]=[document.getElementById(\"left_\").options[i].value,document.getElementById(\"left_\").options[i].text];\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"right_\").length=document.getElementById(\"right_\").length;\r\n");
      out.write("\tfor(var i=0;i<con_data.length;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar con_fla=true;\r\n");
      out.write("\t\tfor(var k=0;k<document.getElementById(\"right_\").length;k++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(con_data[i][0]==document.getElementById(\"right_\").options[k].value)\r\n");
      out.write("\t\t\t\tcon_fla=false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(con_fla)\r\n");
      out.write("\t\t\tdocument.getElementById(\"right_\").options[document.getElementById(\"right_\").length]=new Option(con_data[i][1],con_data[i][0]);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function del_right()\r\n");
      out.write("{\r\n");
      out.write("\tvar index_data=[];\r\n");
      out.write("\tfor(var i=0;i<document.getElementById(\"right_\").length;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(document.getElementById(\"right_\").options[i].selected)\r\n");
      out.write("\t\t\tindex_data[index_data.length]=[i];\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfor(var i=index_data.length-1;i>=0;i--)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"right_\").removeChild(document.getElementById(\"right_\").options[index_data[i]]);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction load_allemployees(employee_type){\r\n");
      out.write("\t        var url = \"onLoadEmployee.do\";\r\n");
      out.write("\t        var p_data = \"employee_type=\" + employee_type;\r\n");
      out.write("\t        doAjaxSubmit(url, p_data, filSelect);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction filSelect(data){\r\n");
      out.write("\t$(\"#left_\").empty();\r\n");
      out.write("\tvar employeeArr = document.getElementById('left_');\r\n");
      out.write("\tfor(var i=0;i<data.length;i++)\r\n");
      out.write("\t{\r\n");
      out.write("               var op = document.createElement(\"OPTION\");\r\n");
      out.write("                op.value = data[i].user_id; \r\n");
      out.write("                op.innerHTML =data[i].user_name;\r\n");
      out.write("               employeeArr.appendChild(op);\r\n");
      out.write(" \r\n");
      out.write("    }\r\n");
      out.write("\t}\r\n");
      out.write("    function doAjaxSubmit(p_url, p_data, p_callback) {\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            type:\"POST\",\r\n");
      out.write("            url: p_url,\r\n");
      out.write("            data: p_data,\r\n");
      out.write("            dataType:\"json\",\r\n");
      out.write("            success: function(data){\r\n");
      out.write("                p_callback(data);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("  $(function(){\r\n");
      out.write("       if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${parentOrganId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"==0){\r\n");
      out.write("\t\t$(\"#parentOrgan\").attr(\"disabled\",\"disabled\"); \r\n");
      out.write("        }\r\n");
      out.write("     });\r\n");
      out.write("\tfunction btn_submit_editDeptTree(){\r\n");
      out.write("\t\t\tvar node = $('#dept').treegrid('getSelected');\r\n");
      out.write("\t\t\tif (node){\r\n");
      out.write("\t\t\t\twindow.location.href=\"");
      out.print(path);
      out.write("/admin/updateDeptTreeOnload.do?organId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&deptId=\"+node.deptId; \r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\talert('请至少选择一条记录！');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction btn_submit_deleteDeptTree(){\r\n");
      out.write("\t\t\tvar node = $('#dept').treegrid('getSelected');\r\n");
      out.write("\t\t\tif (node){\r\n");
      out.write("\t\t\t var msg = \"确认要删除记录吗?\";\r\n");
      out.write("         if(!confirmWindow(msg)){\r\n");
      out.write("         return;\r\n");
      out.write("         }\r\n");
      out.write("            $.ajax({\r\n");
      out.write("            type:\"POST\",\r\n");
      out.write("            url: \"checkChildDept.do\",\r\n");
      out.write("            data: \"deptId=\"+node.deptId,\r\n");
      out.write("            dataType:\"json\",\r\n");
      out.write("            success: function(data){\r\n");
      out.write("            if(data>0){\r\n");
      out.write("            alert('该部门存在下级部门，请先删除下级部门在删除该部门！');\r\n");
      out.write("            return;\r\n");
      out.write("            }else\r\n");
      out.write("            {\r\n");
      out.write("           window.location.href=\"");
      out.print(path);
      out.write("/admin/deleteDeptTree.do?userId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${GLOBAL_SESSION_USER.user_id  }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&organId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&deptId=\"+node.deptId; \r\n");
      out.write("            }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\talert('请至少选择一条记录！');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("       function checkInputGroupName(){\r\n");
      out.write("       var groupName=$('#groupName').val();\r\n");
      out.write("       if(groupName.length>100){\r\n");
      out.write("       alert('你输入的组织名称过长，请重新输入！');\r\n");
      out.write("       $('#groupName').val(\"\");\r\n");
      out.write("       $('#groupName').focus();\r\n");
      out.write("       }\r\n");
      out.write("       }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form method=\"post\" action=\"/organEmployee\">\r\n");
      out.write("<div style=\"width:90%; height:100px\">\r\n");
      out.write(" <input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${GLOBAL_SESSION_USER.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"tuOafOrganTreeTO.fcu\"/>\r\n");
      out.write(" <input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${GLOBAL_SESSION_USER.user_id  }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"tuOafOrganTreeTO.lcu\"/>\r\n");
      out.write(" <input type=\"hidden\"  name=\"organId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write(" ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"90%\" >\r\n");
      out.write("\t <tr>\r\n");
      out.write("\t\t<th class=\"title\" colspan=\"2\">Basic</th>\t\t\t\t\t\t\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("  \t<th scope=\"row\" abbr=\"G5 Processor\" class=\"specalt\" align=\"center\">Parent GroupName:</th>\r\n");
      out.write("    <td class=\"common\">\r\n");
      out.write("    <select id=\"parentOrgan\" name=\"tuOafOrganTreeTO.parent_id\">\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </select>\r\n");
      out.write("     ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write(" \r\n");
      out.write("  <tr>\r\n");
      out.write("  <th  scope=\"row\" abbr=\"G5 Processor\" class=\"specalt\" align=\"center\">GroupName:</th>\r\n");
      out.write("    <td class=\"tdcommon\"><input type=\"text\" id=\"groupName\" name=\"tuOafOrganTreeTO.organ_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organTreeTO.organ_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" onblur=\"checkInputGroupName();\"/></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("  \t<th  scope=\"row\" abbr=\"G5 Processor\" class=\"specalt\" align=\"center\">Group Level:</th>\r\n");
      out.write("    <td class=\"tdcommon\">\r\n");
      out.write("    <select name=\"tuOafOrganTreeTO.type_id\">\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </select>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("  <th scope=\"row\" abbr=\"G5 Processor\" class=\"specalt\" align=\"center\">Is outsourcing dept:</th>\r\n");
      out.write("  <td class=\"tdcommon\"><input type=\"checkbox\" name=\"tuOafOrganTreeTO.is_external\" value=\"Y\" ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("   ></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:90%; height:auto; margin-top: 5px\">\r\n");
      out.write("<div>\r\n");
      out.write(" <table id=\"dept\" title=\"Dept\" class=\"easyui-treegrid\" style=\"width:845px;height:200px\"\r\n");
      out.write("  url=\"");
      out.print(path);
      out.write("/admin/loadDept.do?organId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" idField=\"deptId\" treeField=\"deptName\" nowrap=false animate=true collapsible=true fitColumns=true>\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th field=\"deptName\" width=\"150\">DeptName</th>\r\n");
      out.write("\t\t\t\t<th field=\"deptOwenr\" width=\"150\">DeptOwner</th>\r\n");
      out.write("\t\t\t\t<th field=\"deptType\" width=\"150\">DeptType</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write(" <input  type=\"button\" style=\"width:100px\" value=\"新增\" onClick=\"btn_submit_addDeptTree()\"/></input>\r\n");
      out.write(" <input  type=\"button\" style=\"width:100px\" value=\"编辑\" onClick=\"btn_submit_editDeptTree()\"/></input>\r\n");
      out.write(" <input  type=\"button\" style=\"width:100px\" value=\"删除\" onClick=\"btn_submit_deleteDeptTree()\"/></input>\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\" width:90%; height:100px;margin-top: 5px;\">\r\n");
      out.write(" <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"90%\">\r\n");
      out.write(" \t <tr>\r\n");
      out.write("\t\t<th class=\"title\" colspan=\"2\">System Setting</th>\t\t\t\t\t\t\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("  <th  scope=\"row\" abbr=\"G5 Processor\" class=\"specalt\" align=\"center\"><input  type=\"button\" value=\"Group Type Setting\" onclick=\"btn_submit_grouptypesetting()\"/></th>\r\n");
      out.write("  </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("  <th  scope=\"row\" abbr=\"G5 Processor\" class=\"specalt\" align=\"center\"><input  type=\"button\" value=\"Leader Type Setting\" onclick=\"btn_submit_leadertypesetting()\"/></th>\r\n");
      out.write("  </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:90%; height:auto; margin-top: 5px\">\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write(" <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"90%\">\r\n");
      out.write(" \t <tr>\r\n");
      out.write("\t\t<th class=\"title\" align=\"center\" colspan=\"3\">Leaders&nbsp;&nbsp;</th>\t\t\t\t\t\t\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("  <th  scope=\"row\" abbr=\"G5 Processor\" class=\"specalt\" align=\"center\">title</th>\r\n");
      out.write("  <th  scope=\"row\" abbr=\"G5 Processor\" class=\"specalt_bt\" align=\"center\">User</th>\r\n");
      out.write("  <th  scope=\"row\" abbr=\"G5 Processor\" class=\"specalt_bt\" align=\"center\">操作</th>\r\n");
      out.write("  </tr>\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("    <td colspan=\"3\">\r\n");
      out.write("   <input  type=\"button\" value=\"新增\" onclick=\"btn_submit_addLeader()\"/></input>\r\n");
      out.write("   </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:90%; height:100px; margin-top: 5px;\">\r\n");
      out.write("<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"90%\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th class=\"title\" align=\"center\">\r\n");
      out.write("Employees in the group\r\n");
      out.write("</th>\r\n");
      out.write("<th class=\"title\" colspan=\"2\" align=\"center\">\r\n");
      out.write("<span>\r\n");
      out.write("<input name=\"employee\" type=\"radio\" onclick=\"load_allemployees('all');\"/>Employees all of company<br/>\r\n");
      out.write("<input name=\"employee\"   type=\"radio\" checked=\"checked\" onclick=\"load_allemployees('not');\"/>Employees not belong to any group\r\n");
      out.write("</span>\r\n");
      out.write("</th>\r\n");
      out.write("</tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td class=\"first\" width=\"180\" align=\"center\" valign=\"middle\">\r\n");
      out.write("    <select name=\"right_\" size=\"10\" multiple=\"multiple\" id=\"right_\" style=\"width:300px;\">\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </select>\r\n");
      out.write("   </td>\r\n");
      out.write("    <td class=\"common\" width=\"101\" align=\"center\" valign=\"middle\"><input type=\"button\" style=\"width:100px\" name=\"Submit\" value=\"<<Add\" onclick=\"right_move()\"/>\r\n");
      out.write("      <br />\r\n");
      out.write("      <br />\r\n");
      out.write("    <input type=\"button\" name=\"Submit2\" style=\"width:100px\" value=\"Remove>>\" onclick=\"del_right();\" /></td>\r\n");
      out.write("    <td class=\"common\" width=\"180\" align=\"center\" valign=\"middle\">\r\n");
      out.write("     <select name=\"left_\" size=\"10\" multiple=\"multiple\" id=\"left_\" style=\"width:300px;\">\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </select>\r\n");
      out.write("        </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("  </div>\r\n");
      out.write("<div style=\"width:90%; margin-top:10px\">\r\n");
      out.write("  <input type=\"button\" style=\"width:100px\" value=\"AddSub Group\" onclick=\"btn_submit_addsubgrop()\"/>&nbsp;&nbsp;\r\n");
      out.write("  <input type=\"button\" style=\"width:100px\" value=\"Save\" onclick=\"btn_submit_save()\"/>&nbsp;&nbsp;\r\n");
      out.write("  <input type=\"button\" style=\"width:100px\" value=\"Delete\" onclick=\"btn_submit_deletegrouptype()\"/>\r\n");
      out.write(" </div>\r\n");
      out.write("</form>\r\n");
      out.write(" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /admin/page_admin_organ.jsp(256,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${parentOrganId==0}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write(" <input type=\"hidden\"  name=\"tuOafOrganTreeTO.parent_id\" value=\"0\">\r\n");
          out.write(" ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fif_005f0_reused) {
        _jspx_th_c_005fif_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /admin/page_admin_organ.jsp(269,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("o");
      // /admin/page_admin_organ.jsp(269,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organTree}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.organ_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write(' ');
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.organ_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</option>\r\n");
            out.write("    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fforEach_005f0_reused) {
        _jspx_th_c_005fforEach_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /admin/page_admin_organ.jsp(270,35) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.organ_id ==parentOrganId}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      if (!_jspx_th_c_005fif_005f1_reused) {
        _jspx_th_c_005fif_005f1.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f1);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /admin/page_admin_organ.jsp(273,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${parentOrganId==0}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <span style=\"color:#FF0000\">不能修改总机构的父级机构！</span>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      if (!_jspx_th_c_005fif_005f2_reused) {
        _jspx_th_c_005fif_005f2.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f2);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /admin/page_admin_organ.jsp(287,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("organ");
      // /admin/page_admin_organ.jsp(287,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organTypeName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organ.type_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write(' ');
            if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organ.type_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</option>\r\n");
            out.write("    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      if (!_jspx_th_c_005fforEach_005f1_reused) {
        _jspx_th_c_005fforEach_005f1.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f1);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /admin/page_admin_organ.jsp(288,38) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organ.type_id ==organTreeTO.type_id}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      if (!_jspx_th_c_005fif_005f3_reused) {
        _jspx_th_c_005fif_005f3.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f3);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /admin/page_admin_organ.jsp(295,92) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organTreeTO.is_external=='Y' }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("checked=\"checked\"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      if (!_jspx_th_c_005fif_005f4_reused) {
        _jspx_th_c_005fif_005f4.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f4);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /admin/page_admin_organ.jsp(347,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("l");
      // /admin/page_admin_organ.jsp(347,3) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${leader}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("   <tr>\r\n");
            out.write("    <td class=tdfirst>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${l.type_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("    <td class=\"tdcommon\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${l.user_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("    <td class=\"tdcommon\"><a href=\"editLeaderOnload.do?linkId=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${l.link_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("&organId=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${l.organ_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\">编辑</a>&nbsp;&nbsp;<a href=\"deleteLeader.do?linkId=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${l.link_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("&organId=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${l.organ_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" onclick=\"return confirm('确定要删除吗？')\">删除</a> </td>\r\n");
            out.write("  </tr>\r\n");
            out.write("    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      if (!_jspx_th_c_005fforEach_005f2_reused) {
        _jspx_th_c_005fforEach_005f2.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f2);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent(null);
      // /admin/page_admin_organ.jsp(380,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("in");
      // /admin/page_admin_organ.jsp(380,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeesInTheGroup }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("   <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${in.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(' ');
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${in.user_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(" </option>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      if (!_jspx_th_c_005fforEach_005f3_reused) {
        _jspx_th_c_005fforEach_005f3.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f3);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f4_reused = false;
    try {
      _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f4.setParent(null);
      // /admin/page_admin_organ.jsp(391,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setVar("all");
      // /admin/page_admin_organ.jsp(391,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeNotBelongToAnyGroup }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
        if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("        <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${all.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(' ');
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${all.user_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(" </option>\r\n");
            out.write("   ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f4);
      _jspx_th_c_005fforEach_005f4_reused = true;
    } finally {
      if (!_jspx_th_c_005fforEach_005f4_reused) {
        _jspx_th_c_005fforEach_005f4.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f4);
      }
    }
    return false;
  }
}
