/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2019-03-07 00:19:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.train;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\t<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\r\n");
      out.write("    <title>登录</title>\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/train/images/fav.ico\" />\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/train/css/login.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"overflow:hidden\">\r\n");
      out.write("\t<!--<div class=\"bg\"></div>-->\r\n");
      out.write("    <div class=\"pagewrap\">\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <div class=\"con_right\">\r\n");
      out.write("                    <div class=\"con_r_top\">\r\n");
      out.write("                    \t<a href=\"javascript:;\" class=\"left\" style=\"color: #5d5a5a; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(46, 85, 142);\"><b>登录管理</b></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"reMessage\">\r\n");
      out.write("                    \t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requesMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"con_r_left\" style=\"display: block;\">\r\n");
      out.write("                            <form name=\"form1\" method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/login.do\" autocomplete=\"off\">\r\n");
      out.write("                                <div class=\"user\">\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <span class=\"user-icon\"></span>\r\n");
      out.write("                                        <input type=\"text\" id=\"userid\" name=\"userid\" placeholder=\"　输入账号\" value=\"\" autocomplete=\"off\"/>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <span class=\"mima-icon\"></span>\r\n");
      out.write("                                        <input type=\"password\" id=\"pwd\" name=\"pwd\" placeholder=\"　输入密码\" value=\"\" autocomplete=\"off\"/>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <span class=\"yzmz-icon\"></span>\r\n");
      out.write("                                        <input id=\"vdcode\" type=\"text\" name=\"validate\" placeholder=\"　验证码\" value=\"\" style=\" width:210px;\"/>\r\n");
      out.write("                                        <img style=\"cursor: pointer;margin-left:10px;width:80px;height:33px;\" id=\"captcha\" name=\"captcha\" alt=\"看不清？点击更换\"\r\n");
      out.write("                                         title=\"看不清？点击更换\" src=\"");
      out.print(request.getContextPath());
      out.write("/authCode.do\"/>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write(" \r\n");
      out.write("                                <button id=\"btn_Login\" type=\"submit\">登 录</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div style=\"position:absolute;bottom:5px;width:100%;text-align:center;color:#5d5a5a;font-size:14px;font-weight:bold\">\r\n");
      out.write("        \t版本：V1.1.9-2019年3月6日<br>&copy 南京高铁信息科技有限公司 2018 All Rights Reserveda\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/train/js/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/train/js/login.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/train/js/jquery.particleground.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\t    $(function(){\r\n");
      out.write("\t    \t$(\"#captcha\").click(function(){\r\n");
      out.write("\t    \t\t$(this).attr(\"src\",'");
      out.print(request.getContextPath());
      out.write("/authCode.do?'+new Date().getTime());\r\n");
      out.write("\t    \t\t$(\"#reMessage\").html(\"<font color='red'> </font>\");\r\n");
      out.write("\t    \t})\r\n");
      out.write("\t    });\r\n");
      out.write("\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function () {\r\n");
      out.write("          particleground(document.getElementsByTagName('body')[0], {\r\n");
      out.write("            dotColor: '#5cbdaa',\r\n");
      out.write("            lineColor: '#5cbdaa'\r\n");
      out.write("          });\r\n");
      out.write("        }, false);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("          $('body').particleground({\r\n");
      out.write("            dotColor: '#5cbdaa',\r\n");
      out.write("            lineColor: '#5cbdaa'\r\n");
      out.write("          });\r\n");
      out.write("          $('.intro').css({\r\n");
      out.write("            'margin-top': -($('.intro').height() / 2)\r\n");
      out.write("          });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
